/* Body file for function obcp_engine
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "obcp_engine.h"
//#include <stdio.h>

#ifndef OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS
#define OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS (8)
#endif

#ifndef OBCP_MAXIMUM_NUMBER_OF_REGISTERED_OBCP_WORKERS
#define OBCP_MAXIMUM_NUMBER_OF_REGISTERED_OBCPS_WORKERS (8)
#endif

typedef struct
{
    bool loaded;
    asn1SccOBCP_Id id;
    asn1SccOBCP_Code code;
    asn1SccOBCP_Execution_Status status;
} OBCP_Procedure;

static OBCP_Procedure obcps[OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS] = {};
static uint32_t obcps_count = 0;

typedef struct
{
    bool registered;
    bool used;
    asn1SccPID pid;
    asn1SccOBCP_Id obcp_id;
    uintptr_t native_thread_handle;
} OBCP_Worker;

static OBCP_Worker workers[OBCP_MAXIMUM_NUMBER_OF_REGISTERED_OBCPS_WORKERS] = {};
static uint32_t workers_count = 0;

void obcp_engine_startup(void)
{
    obcps_count = 0;
    for (uint32_t i = 0; i < OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS; i++)
    {
        obcps[i].loaded = 0;
    }
    workers_count = 0;
    for (uint32_t i = 0; i < OBCP_MAXIMUM_NUMBER_OF_REGISTERED_OBCPS_WORKERS; i++)
    {
        workers[i].registered = 0;
    }
}

void obcp_engine_PI_abort_obcp
      (const asn1SccOBCP_Id *IN_id,
       asn1SccT_Boolean *OUT_success)

{
   // Write your code here
}


void obcp_engine_PI_activate_obcp
      (const asn1SccOBCP_Id *IN_id,
       asn1SccT_Boolean *OUT_success)

{
   // Write your code here
}


void obcp_engine_PI_can_obcp_be_activated
      (const asn1SccOBCP_Id *IN_id,
       asn1SccT_Boolean *OUT_success)

{
   // Write your code here
}


void obcp_engine_PI_can_obcp_be_loaded
      (const asn1SccOBCP_Id *IN_id,
       asn1SccT_Boolean *OUT_success)

{
   // Write your code here
}


void obcp_engine_PI_get_obcp_status
      (const asn1SccOBCP_Id *IN_id,
       asn1SccOBCP_Execution_Status *OUT_execution_status,
       asn1SccT_Boolean *OUT_success)

{
   // Write your code here
}


void obcp_engine_PI_load_obcp
      (const asn1SccOBCP_Id *IN_id,
       const asn1SccOBCP_Code *IN_code,
       asn1SccT_Boolean *OUT_success)

{
   // Write your code here
}


void obcp_engine_PI_receive_packet
      (const asn1SccOBCP_Channel_Id *IN_channel,
       const asn1SccOBCP_Packet *IN_packet)

{
   // Write your code here
}


void obcp_engine_PI_start_obcp_engine(void)
{
   // Write your code here
}


void obcp_engine_PI_stop_obcp
      (const asn1SccOBCP_Id *IN_id,
       asn1SccT_Boolean *OUT_success)

{
   // Write your code here
}


void obcp_engine_PI_stop_obcp_engine(void)
{
   // Write your code here
}


void obcp_engine_PI_unload_obcp
      (const asn1SccOBCP_Id *IN_id,
       asn1SccT_Boolean *OUT_success)

{
   // Write your code here
}


