/* Body file for function obcp_engine
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "obcp_engine.h"
#include "obcp_engine_thread_local.h"
#include <string.h>

/* Forward declarations for HAL functions (provided by the TASTE runtime). */
extern bool     Hal_SleepNs(uint64_t time_ns);
extern uint64_t Hal_GetElapsedTimeInNs(void);
extern int32_t  Hal_SemaphoreCreate(void);
extern bool     Hal_SemaphoreObtain(int32_t id);
extern bool     Hal_SemaphoreRelease(int32_t id);

#define MS_PER_SECOND     (1000U)
#define NS_PER_MS         (1000000ULL)

#define DEBUG

#if defined(DEBUG) && defined(__unix__) 
#include <stdio.h>
#define DEBUG_PRINT(...) printf(__VA_ARGS__)
#else
#define DEBUG_PRINT(...) ((void)0)
#endif

/* Include obcpengine header from n7s-obcp */
#include "obcpengine.h"

#ifndef OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS
#define OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS (8)
#endif

#ifndef OBCP_MAXIMUM_NUMBER_OF_REGISTERED_OBCP_WORKERS
#define OBCP_MAXIMUM_NUMBER_OF_REGISTERED_OBCPS_WORKERS (8)
#endif

#ifndef OBCP_MICROPYTHON_HEAP_SIZE
#define OBCP_MICROPYTHON_HEAP_SIZE (65536)
#endif

#ifndef OBCP_PACKET_CHANNEL_COUNT
#define OBCP_PACKET_CHANNEL_COUNT (4)
#endif

/* Polling interval used when a finite receive timeout is requested (10 ms). */
#define PACKET_POLL_INTERVAL_NS  (10000000ULL)

/* Sentinel: pass as timeout_ms to obcp_receive_packet for an indefinite
 * blocking wait (unblocked by an incoming packet via the channel semaphore). */
#define OBCP_RECEIVE_TIMEOUT_BLOCKING  (~(uint32_t)0U)

typedef struct
{
   bool loaded;
   asn1SccOBCP_Id id;
   asn1SccOBCP_Code code;
   asn1SccOBCP_Execution_Status status;
} OBCP_Procedure;

static OBCP_Procedure obcps[OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS] = {};
static uint32_t obcps_count = 0;

typedef struct
{
   bool registered;
   bool used;
   asn1SccPID pid;
   asn1SccOBCP_Id obcp_id;
   uintptr_t native_thread_handle;
   /* Union forces alignment to at least sizeof(uintptr_t), which is required
    * by the MicroPython GC (VERIFY_PTR asserts word-aligned pointers). */
   union {
      char     bytes[OBCP_MICROPYTHON_HEAP_SIZE];
      uintptr_t _align;
   } heap;
} OBCP_Worker;

static OBCP_Worker workers[OBCP_MAXIMUM_NUMBER_OF_REGISTERED_OBCPS_WORKERS] = {};
static uint32_t workers_count = 0;

/* ===================================================================
 * Per-channel packet inlet buffer
 * ===================================================================
 * Each channel holds at most one packet at a time.  A Hal semaphore
 * (initially 0) allows a receiver to block until a packet arrives.
 * obcp_engine_PI_receive_packet stores the incoming packet and calls
 * Hal_SemaphoreRelease; wrapper_receive_packet consumes it.
 * =================================================================== */

typedef struct
{
   asn1SccOBCP_Packet packet;
   bool               occupied;
   int32_t            data_semaphore_id;  /* released on arrival, obtained by receiver */
   int32_t            space_semaphore_id; /* obtained before writing, released after consuming */
} OBCP_PacketChannel;

static OBCP_PacketChannel packet_channels[OBCP_PACKET_CHANNEL_COUNT];

static inline int32_t get_worker_id_by_pid(const asn1SccPID pid)
{
   for (int32_t id = 0; id < (int32_t)workers_count; id++)
   {
      if (workers[id].pid == pid)
      {
         return id;
      }
   }
   return -1;
}

static inline void clear_engine()
{
   obcps_count = 0;
   for (uint32_t i = 0; i < OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS; i++)
   {
      obcps[i].loaded = 0;
   }
   workers_count = 0;
   for (uint32_t i = 0; i < OBCP_MAXIMUM_NUMBER_OF_REGISTERED_OBCPS_WORKERS; i++)
   {
      workers[i].registered = 0;
      workers[i].used = 0;
   }
}

/* ===================================================================
 * Wrapper functions to route obcpengine calls to TASTE RI functions
 * =================================================================== */

/* Wrapper for send_event */
static void wrapper_send_event(const uint32_t event_id)
{
   asn1SccOBCP_Event_Id id = event_id;
   obcp_engine_RI_send_event(&id);
}

/* Wrapper for output_message */
static bool wrapper_output_message(const char *text, size_t length)
{
   asn1SccOBCP_Text msg;
   /* Ensure we don't overflow the buffer (max 32 chars + null terminator) */
   size_t copy_len = (length < 32) ? length : 32;
   memcpy(msg, text, copy_len);
   msg[copy_len] = '\0';
   obcp_engine_RI_output_message(&msg);
   return true;
}

/* Wrapper for get_current_time */
static bool wrapper_get_current_time(uint32_t *seconds, uint32_t *milliseconds)
{
   asn1SccT_Int32 sec, msec;
   obcp_engine_RI_get_current_time(&sec, &msec);
   *seconds = (uint32_t)sec;
   *milliseconds = (uint32_t)msec;
   return true;
}

/* Wrapper for wait (relative delay in milliseconds) */
static bool wrapper_wait(const uint32_t milliseconds)
{
   return Hal_SleepNs((uint64_t)milliseconds * NS_PER_MS);
}

/* Wrapper for waituntil (absolute time in seconds + milliseconds) */
static bool wrapper_waituntil(const uint32_t target_seconds, const uint32_t target_milliseconds)
{
   const uint64_t target_ns = ((uint64_t)target_seconds * MS_PER_SECOND + target_milliseconds) * NS_PER_MS;
   const uint64_t now_ns    = Hal_GetElapsedTimeInNs();
   if (target_ns <= now_ns)
   {
      return true;
   }
   return Hal_SleepNs(target_ns - now_ns);
}

/* Wrapper for read_int_parameter */
static bool wrapper_read_int_parameter(const uint32_t id, int32_t *value)
{
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Type param_type = OBCP_Parameter_Type_integer_type;
   asn1SccOBCP_Parameter_Value param_value;

   obcp_engine_RI_get_parameter_value(&param_id, &param_type, &param_value);

   if (param_value.kind == OBCP_Parameter_Value_int_value_PRESENT)
   {
      *value = (int32_t)param_value.u.int_value;
      return true;
   }
   return false;
}

/* Wrapper for write_int_parameter */
static bool wrapper_write_int_parameter(const uint32_t id, const int32_t value)
{
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Value param_value;
   param_value.kind = OBCP_Parameter_Value_int_value_PRESENT;
   param_value.u.int_value = (asn1SccT_Int32)value;

   obcp_engine_RI_set_parameter_value(&param_id, &param_value);
   return true;
}


/* Wrapper for read_enum_parameter */
static bool wrapper_read_enum_parameter(const uint32_t id, int32_t *value)
{
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Type param_type = OBCP_Parameter_Type_enumerated_type;
   asn1SccOBCP_Parameter_Value param_value;

   obcp_engine_RI_get_parameter_value(&param_id, &param_type, &param_value);

   if (param_value.kind == OBCP_Parameter_Value_enum_value_PRESENT)
   {
      *value = (int32_t)param_value.u.enum_value;
      return true;
   }
   return false;
}

/* Wrapper for write_enum_parameter */
static bool wrapper_write_enum_parameter(const uint32_t id, const int32_t value)
{
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Value param_value;
   param_value.kind = OBCP_Parameter_Value_enum_value_PRESENT;
   param_value.u.enum_value = (asn1SccT_Int32)value;

   obcp_engine_RI_set_parameter_value(&param_id, &param_value);
   return true;
}

/* Wrapper for read_float_parameter */
static bool wrapper_read_float_parameter(const uint32_t id, float *value)
{
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Type param_type = OBCP_Parameter_Type_float_type;
   asn1SccOBCP_Parameter_Value param_value;

   obcp_engine_RI_get_parameter_value(&param_id, &param_type, &param_value);

   if (param_value.kind == OBCP_Parameter_Value_float_value_PRESENT)
   {
      *value = (float)param_value.u.float_value;
      return true;
   }
   return false;
}

/* Wrapper for write_float_parameter */
static bool wrapper_write_float_parameter(const uint32_t id, const float value)
{
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Value param_value;
   param_value.kind = OBCP_Parameter_Value_float_value_PRESENT;
   param_value.u.float_value = (asn1SccT_Float32)value;

   obcp_engine_RI_set_parameter_value(&param_id, &param_value);
   return true;
}

/* Wrapper for read_bool_parameter */
static bool wrapper_read_bool_parameter(const uint32_t id, bool *value)
{
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Type param_type = OBCP_Parameter_Type_boolean_type;
   asn1SccOBCP_Parameter_Value param_value;

   obcp_engine_RI_get_parameter_value(&param_id, &param_type, &param_value);

   if (param_value.kind == OBCP_Parameter_Value_bool_value_PRESENT)
   {
      *value = (bool)param_value.u.bool_value;
      return true;
   }
   return false;
}

/* Wrapper for write_bool_parameter */
static bool wrapper_write_bool_parameter(const uint32_t id, const bool value)
{
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Value param_value;
   param_value.kind = OBCP_Parameter_Value_bool_value_PRESENT;
   param_value.u.bool_value = (asn1SccT_Boolean)value;

   obcp_engine_RI_set_parameter_value(&param_id, &param_value);
   return true;
}

/* ===================================================================
 * Packet wrapper functions
 * =================================================================== */

/* Returns true when a packet is buffered on the given channel. */
static bool wrapper_is_packet_available(const uint32_t channel)
{
   if (channel >= OBCP_PACKET_CHANNEL_COUNT)
   {
      return false;
   }
   return packet_channels[channel].occupied;
}

/* Returns the index of the first channel that currently has a packet,
 * or false when none do. */
static bool wrapper_get_channel_with_packet_available(uint32_t *channel)
{
   for (uint32_t i = 0; i < OBCP_PACKET_CHANNEL_COUNT; ++i)
   {
      if (packet_channels[i].occupied)
      {
         *channel = i;
         return true;
      }
   }
   return false;
}

/* Output path: packets are always forwarded directly to the TASTE RI,
 * so a valid channel can always accept a send request. */
static bool wrapper_can_send_packet(const uint32_t channel)
{
   return channel < OBCP_PACKET_CHANNEL_COUNT;
}

/* Forward the packet to the TASTE harness via the send_packet RI. */
static bool wrapper_send_packet(const uint32_t channel,
                                const uint32_t length,
                                const char *const data)
{
   asn1SccOBCP_Channel_Id ch_id  = (asn1SccOBCP_Channel_Id)channel;
   asn1SccOBCP_Packet     packet;
   asn1SccT_Boolean       success = FALSE;

   uint32_t copy_len = length;
   if (copy_len > (uint32_t)sizeof(packet.arr))
   {
      copy_len = (uint32_t)sizeof(packet.arr);
   }
   memcpy(packet.arr, data, copy_len);
   packet.nCount = (int)copy_len;

   obcp_engine_RI_send_packet(&ch_id, &packet, &success);
   return (bool)success;
}

/* Receive a packet from the inlet buffer.
 *
 * timeout_milliseconds == 0                    : non-blocking check.
 * timeout_milliseconds == OBCP_RECEIVE_TIMEOUT_BLOCKING : block indefinitely
 *                          using the channel semaphore; unblocked via
 *                          Hal_SemaphoreRelease in obcp_engine_PI_receive_packet.
 * 0 < timeout_milliseconds < OBCP_RECEIVE_TIMEOUT_BLOCKING : poll with
 *                          Hal_SleepNs until a packet arrives or the
 *                          deadline is exceeded.
 */
static bool wrapper_receive_packet(const uint32_t channel,
                                   uint32_t *length,
                                   char *data,
                                   uint32_t timeout_milliseconds)
{
   if (channel >= OBCP_PACKET_CHANNEL_COUNT)
   {
      return false;
   }

   OBCP_PacketChannel *ch = &packet_channels[channel];

   if (timeout_milliseconds == 0U)
   {
      /* Non-blocking: return immediately if no packet is present. */
      if (!ch->occupied)
      {
         return false;
      }
   }
   else if (timeout_milliseconds == OBCP_RECEIVE_TIMEOUT_BLOCKING)
   {
      /* Blocking wait: Hal_SemaphoreObtain blocks until
       * obcp_engine_PI_receive_packet calls Hal_SemaphoreRelease.
       * If a packet was already present before we get here the previous
       * release will have incremented the semaphore count, so Obtain
       * returns immediately — no packet is missed. */
      if (!ch->occupied)
      {
         Hal_SemaphoreObtain(ch->data_semaphore_id);
      }
   }
   else
   {
      /* Timed wait: poll at PACKET_POLL_INTERVAL_NS intervals. */
      const uint64_t deadline_ns =
          Hal_GetElapsedTimeInNs() +
          (uint64_t)timeout_milliseconds * NS_PER_MS;

      while (!ch->occupied)
      {
         if (Hal_GetElapsedTimeInNs() >= deadline_ns)
         {
            return false;
         }
         Hal_SleepNs(PACKET_POLL_INTERVAL_NS);
      }
   }

   if (!ch->occupied)
   {
      /* Spurious wakeup — no packet available. */
      return false;
   }

   /* Consume the buffered packet. */
   uint32_t copy_len = (uint32_t)ch->packet.nCount;
   if (copy_len > *length)
   {
      copy_len = *length;
   }
   memcpy(data, ch->packet.arr, copy_len);
   *length = copy_len;
   ch->occupied = false;

   /* Signal that the slot is free for the next incoming packet. */
   Hal_SemaphoreRelease(ch->space_semaphore_id);

   return true;
}

/* Compare two OBCP ids without relying on null termination. */
static bool isObcpIdEqual(const asn1SccOBCP_Id id1, const asn1SccOBCP_Id id2)
{
   size_t n = sizeof(asn1SccOBCP_Id);
   for (size_t i = 0; i < n; ++i)
   {
      if (id1[i] != id2[i])
      {
         return false;
      }
   }
   return true;
}

/* Return index into `obcps` array for given id, or -1 if not found. */
static int32_t getObcpIndex(const asn1SccOBCP_Id id)
{
   for (uint32_t i = 0; i < OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS; ++i)
   {
      if (obcps[i].loaded && isObcpIdEqual(obcps[i].id, id))
      {
         return (int32_t)i;
      }
   }
   return -1;
}

void obcp_engine_startup(void)
{
   obcp_engine_tls_init();
   clear_engine();

   /* Initialise per-channel packet inlet buffers and their semaphores. */
   for (uint32_t i = 0; i < OBCP_PACKET_CHANNEL_COUNT; ++i)
   {
      packet_channels[i].occupied        = false;
      /* data semaphore starts at 0: obtained by receiver, released on arrival */
      packet_channels[i].data_semaphore_id  = Hal_SemaphoreCreate();
      /* space semaphore starts at 1: obtained before writing, released after read */
      packet_channels[i].space_semaphore_id = Hal_SemaphoreCreate();
      Hal_SemaphoreRelease(packet_channels[i].space_semaphore_id);
   }

   /* Initialize obcpengine with callbacks to TASTE RI functions */
   obcp_engine_context_t context = {
       .obcp_engine_get_thread_local_value = obcp_engine_tls_get,
       .obcp_engine_set_thread_local_value = obcp_engine_tls_set,
       .obcp_read_int_parameter = wrapper_read_int_parameter,
       .obcp_write_int_parameter = wrapper_write_int_parameter,
       .obcp_read_enum_parameter = wrapper_read_enum_parameter,
       .obcp_write_enum_parameter = wrapper_write_enum_parameter,
       .obcp_read_float_parameter = wrapper_read_float_parameter,
       .obcp_write_float_parameter = wrapper_write_float_parameter,
       .obcp_read_bool_parameter = wrapper_read_bool_parameter,
       .obcp_write_bool_parameter = wrapper_write_bool_parameter,
       .obcp_send_event = wrapper_send_event,
       .obcp_write = wrapper_output_message,
       .obcp_beginstep = NULL, /* Not implemented yet */
       .obcp_endstep = NULL,   /* Not implemented yet */
       .obcp_wait = wrapper_wait,
       .obcp_waituntil = wrapper_waituntil,
       .obcp_gettime = wrapper_get_current_time,
       .obcp_is_packet_available = wrapper_is_packet_available,
       .obcp_get_channel_with_packet_available = wrapper_get_channel_with_packet_available,
       .obcp_can_send_packet = wrapper_can_send_packet,
       .obcp_send_packet = wrapper_send_packet,
       .obcp_receive_packet = wrapper_receive_packet
   };

   obcpengine_init(&context);
}

void obcp_engine_PI_abort_obcp(const asn1SccOBCP_Id *IN_id,
                               asn1SccT_Boolean *OUT_success)

{
   // TODO
}

extern void obcp_engine_RI_activate_worker_To_PID(asn1SccPID dest_pid, const asn1SccT_Int32 *IN_obcp_index);

void obcp_engine_PI_activate_obcp(const asn1SccOBCP_Id *IN_id,
                                  asn1SccT_Boolean *OUT_success)

{
   *OUT_success = FALSE;

   asn1SccT_Boolean can_activate = FALSE;
   obcp_engine_PI_can_obcp_be_activated(IN_id, &can_activate);
   if (!can_activate)
   {
      return;
   }

   const int32_t obcp_index = getObcpIndex(*IN_id);
   if (obcp_index < 0)
   {
      return;
   }

   for (uint32_t i = 0; i < workers_count; ++i)
   {
      if (workers[i].registered && !workers[i].used)
      {
         workers[i].used = true;
         memcpy(workers[i].obcp_id, *IN_id, sizeof(asn1SccOBCP_Id));

         asn1SccT_Int32 idx = (asn1SccT_Int32)obcp_index;

         DEBUG_PRINT("Sending ACTIVATE to Worker[%d] PID %d\n", i, workers[i].pid);
         obcp_engine_RI_activate_worker_To_PID(workers[i].pid, &idx);

         *OUT_success = TRUE;
         return;
      }
   }
}

void obcp_engine_PI_can_obcp_be_activated(const asn1SccOBCP_Id *IN_id,
                                          asn1SccT_Boolean *OUT_success)

{
   *OUT_success = FALSE;

   if (getObcpIndex(*IN_id) < 0)
   {
      return;
   }

   for (uint32_t i = 0; i < workers_count; ++i)
   {
      if (workers[i].registered && !workers[i].used)
      {
         *OUT_success = TRUE;
         return;
      }
   }
}

void obcp_engine_PI_can_obcp_be_loaded(const asn1SccOBCP_Id *IN_id,
                                       asn1SccT_Boolean *OUT_success)

{
   *OUT_success = FALSE;

   if (obcps_count >= OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS)
   {
      return;
   }

   if (getObcpIndex(*IN_id) >= 0)
   {
      return;
   }

   *OUT_success = TRUE;
}

void obcp_engine_PI_get_obcp_status(const asn1SccOBCP_Id *IN_id,
                                    asn1SccOBCP_Execution_Status *OUT_execution_status,
                                    asn1SccT_Boolean *OUT_success)

{
   *OUT_success = FALSE;
   const int32_t index = getObcpIndex(*IN_id);
   if (index < 0)
   {
      return;
   }
   *OUT_execution_status = obcps[index].status;
   *OUT_success = TRUE;
}

void obcp_engine_PI_load_obcp(const asn1SccOBCP_Id *IN_id,
                              const asn1SccOBCP_Code *IN_code,
                              asn1SccT_Boolean *OUT_success)

{
   *OUT_success = FALSE;

   asn1SccT_Boolean can_load = FALSE;
   obcp_engine_PI_can_obcp_be_loaded(IN_id, &can_load);
   if (!can_load)
   {
      return;
   }

   for (uint32_t id = 0; id < OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS; ++id)
   {
      if (!obcps[id].loaded)
      {
         memcpy(obcps[id].id, *IN_id, sizeof(asn1SccOBCP_Id));
         for (int i = 0; i < IN_code->nCount; i++)
         {
            obcps[id].code.arr[i] = IN_code->arr[i];
         }
         obcps[id].code.nCount = IN_code->nCount;
         obcps[id].status = OBCP_Execution_Status_inactive;
         obcps[id].loaded = true;
         ++obcps_count;
         *OUT_success = TRUE;
         return;
      }
   }
}

void obcp_engine_PI_receive_packet(const asn1SccOBCP_Channel_Id *IN_channel,
                                   const asn1SccOBCP_Packet *IN_packet)
{
   const uint32_t ch_idx = (uint32_t)*IN_channel;
   if (ch_idx >= OBCP_PACKET_CHANNEL_COUNT)
   {
      return;
   }

   OBCP_PacketChannel *ch = &packet_channels[ch_idx];

   /* Block until the slot is free (space semaphore count > 0). */
   Hal_SemaphoreObtain(ch->space_semaphore_id);

   /* Store the incoming packet, overwriting any previously unread packet
    * on the same channel (1-packet-deep inlet buffer per channel). */
   ch->packet   = *IN_packet;
   ch->occupied = true;

   /* Unblock any receiver that is waiting on this channel's data semaphore. */
   Hal_SemaphoreRelease(ch->data_semaphore_id);
}

void obcp_engine_PI_start_obcp_engine(void)
{
   clear_engine();
   obcp_engine_RI_initiate_registration();
}

void obcp_engine_PI_stop_obcp(const asn1SccOBCP_Id *IN_id,
                              asn1SccT_Boolean *OUT_success)

{
   // TODO Issue stop to the indicated OBCP and wait until its worker is stopped
}

void obcp_engine_PI_stop_obcp_engine(void)
{
    // TODO Issue abort to all active OBCPS and wait untill all workers are freed
}

void obcp_engine_PI_unload_obcp(const asn1SccOBCP_Id *IN_id,
                                asn1SccT_Boolean *OUT_success)

{
   *OUT_success = FALSE;

   const int32_t index = getObcpIndex(*IN_id);
   if (index < 0)
   {
      return;
   }

   if (obcps[index].status != OBCP_Execution_Status_inactive)
   {
      return;
   }

   obcps[index].loaded = false;
   obcps[index].code.nCount = 0;
   --obcps_count;
   *OUT_success = TRUE;
}

extern asn1SccPID obcp_engine_do_work_get_sender();

void obcp_engine_PI_do_work(const asn1SccT_Int32 *obcp_index)
{
   const uint32_t idx = (uint32_t)(*obcp_index);
   const asn1SccPID pid = obcp_engine_do_work_get_sender();

   if (idx >= OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS || !obcps[idx].loaded)
   {
      return;
   }

   obcps[idx].status = OBCP_Execution_Status_active_and_running;
   const int32_t worker_id = get_worker_id_by_pid(pid);

   /* Bind this thread's TLS slot on every do_work entry.  On Linux this is a
    * no-op; on RTEMS/FreeRTOS it is idempotent after the first call. */
   obcp_engine_tls_bind();

   if (worker_id < 0)
   {
      DEBUG_PRINT("DO WORK: unknown worker PID %d — aborting\n", pid);
      obcps[idx].status = OBCP_Execution_Status_inactive;
      return;
   }

   DEBUG_PRINT("DO WORK Worker[%d] PID %d\n", worker_id, pid);

   obcpengine_execute_py(
       (const char *)obcps[idx].code.arr,
       workers[worker_id].heap.bytes,
       OBCP_MICROPYTHON_HEAP_SIZE);

   obcps[idx].status = OBCP_Execution_Status_inactive;
}

extern asn1SccPID obcp_engine_release_worker_get_sender();

void obcp_engine_PI_release_worker(void)
{
   const asn1SccPID pid = obcp_engine_release_worker_get_sender();
   const int32_t id = get_worker_id_by_pid(pid);
   if (id >= 0)
   {
      workers[id].used = false;
   }
   DEBUG_PRINT("RELEASE Worker[%d] PID %d\n", id, pid);
}

extern asn1SccPID obcp_engine_register_worker_get_sender();

void obcp_engine_PI_register_worker()
{
   if (workers_count >= OBCP_MAXIMUM_NUMBER_OF_REGISTERED_OBCPS_WORKERS)
   {
      return;
   }
   const uint32_t id = workers_count++;
   const asn1SccPID pid = obcp_engine_register_worker_get_sender();

   workers[id].pid = pid;
   workers[id].registered = true;
   workers[id].used = false;

   DEBUG_PRINT("REGISTERED Worker[%d] as PID %d\n", id, pid);
}