// Automatically generated by makemoduledefs.py.

#ifndef MP_STATE_PTR
extern const struct _mp_obj_module_t mp_module___main__;
#define MODULE_DEF___MAIN__ { MP_ROM_QSTR(MP_QSTR___main__), MP_ROM_PTR(&mp_module___main__) },
#else
#define MODULE_DEF___MAIN__
#endif

extern const struct _mp_obj_module_t mp_module_builtins;
#undef MODULE_DEF_BUILTINS
#define MODULE_DEF_BUILTINS { MP_ROM_QSTR(MP_QSTR_builtins), MP_ROM_PTR(&mp_module_builtins) },

extern const struct _mp_obj_module_t mp_module_gc;
#undef MODULE_DEF_GC
#define MODULE_DEF_GC { MP_ROM_QSTR(MP_QSTR_gc), MP_ROM_PTR(&mp_module_gc) },

extern const struct _mp_obj_module_t mp_module_obcpcontrol;
#undef MODULE_DEF_OBCPCONTROL
#define MODULE_DEF_OBCPCONTROL { MP_ROM_QSTR(MP_QSTR_obcpcontrol), MP_ROM_PTR(&mp_module_obcpcontrol) },

extern const struct _mp_obj_module_t mp_module_obcpdatapool;
#undef MODULE_DEF_OBCPDATAPOOL
#define MODULE_DEF_OBCPDATAPOOL { MP_ROM_QSTR(MP_QSTR_obcpdatapool), MP_ROM_PTR(&mp_module_obcpdatapool) },

extern const struct _mp_obj_module_t mp_module_obcpevents;
#undef MODULE_DEF_OBCPEVENTS
#define MODULE_DEF_OBCPEVENTS { MP_ROM_QSTR(MP_QSTR_obcpevents), MP_ROM_PTR(&mp_module_obcpevents) },

extern const struct _mp_obj_module_t mp_module_obcpio;
#undef MODULE_DEF_OBCPIO
#define MODULE_DEF_OBCPIO { MP_ROM_QSTR(MP_QSTR_obcpio), MP_ROM_PTR(&mp_module_obcpio) },

extern const struct _mp_obj_module_t mp_module_obcppackets;
#undef MODULE_DEF_OBCPPACKETS
#define MODULE_DEF_OBCPPACKETS { MP_ROM_QSTR(MP_QSTR_obcppackets), MP_ROM_PTR(&mp_module_obcppackets) },

extern const struct _mp_obj_module_t mp_module_obcptime;
#undef MODULE_DEF_OBCPTIME
#define MODULE_DEF_OBCPTIME { MP_ROM_QSTR(MP_QSTR_obcptime), MP_ROM_PTR(&mp_module_obcptime) },


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_BUILTINS \
    MODULE_DEF_GC \
    MODULE_DEF_OBCPCONTROL \
    MODULE_DEF_OBCPDATAPOOL \
    MODULE_DEF_OBCPEVENTS \
    MODULE_DEF_OBCPIO \
    MODULE_DEF_OBCPPACKETS \
    MODULE_DEF_OBCPTIME \
    MODULE_DEF___MAIN__ \
// MICROPY_REGISTERED_MODULES

#define MICROPY_REGISTERED_EXTENSIBLE_MODULES \
// MICROPY_REGISTERED_EXTENSIBLE_MODULES
