/* Body file for function obcp_engine
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "obcp_engine.h"
#include "obcp_engine_thread_local.h"
#include "persistentcode.h"
#include <string.h>
#include <Hal.h>
#include <assert.h>
#include <stdatomic.h>

#define MS_PER_SECOND     (1000U)
#define NS_PER_MS         (1000000ULL)

#if defined(DEBUG) && defined(__unix__)
#include <stdio.h>
#define DEBUG_PRINT(...) printf(__VA_ARGS__)
#else
#define DEBUG_PRINT(...) ((void)0)
#endif

/* Include obcpengine header from n7s-obcp */
#include "obcpengine.h"
#include "obj.h"
#include "runtime.h"

#ifndef OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS
#define OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS (8)
#endif

#ifndef OBCP_MAXIMUM_NUMBER_OF_REGISTERED_OBCP_WORKERS
#define OBCP_MAXIMUM_NUMBER_OF_REGISTERED_OBCP_WORKERS (8)
#endif

#ifndef OBCP_MICROPYTHON_HEAP_SIZE
#define OBCP_MICROPYTHON_HEAP_SIZE (65536)
#endif

/* Packet receive buffer per worker — must be large enough to hold the
 * largest possible OBCP_Packet payload (127 bytes per the ASN.1 model). */
#ifndef OBCP_PACKET_BUFFER_SIZE
#define OBCP_PACKET_BUFFER_SIZE (asn1SccOBCP_Packet_REQUIRED_BYTES_FOR_ENCODING)
#endif

#ifndef OBCP_PACKET_CHANNEL_COUNT
#define OBCP_PACKET_CHANNEL_COUNT (4)
#endif

#define OBCP_MPY_MAGIC_NUMBER          (0x4dU)

/* Polling interval used when a finite receive timeout is requested (10 ms). */
#define PACKET_POLL_INTERVAL_NS  (10000000ULL)

/* Sentinel stored in current_step when no step is in progress. */
#define OBCP_NO_STEP  (~(uint32_t)0U)

typedef struct
{
   /* Written by Protected PIs (load_obcp, clear_obcp) and read by the
    * Unprotected PI_do_work.  Must be atomic_bool so that the release store
    * in PI_load_obcp (after writing code.arr/nCount) pairs with the acquire
    * load in PI_do_work, formally making the code buffer visible to the
    * worker thread without relying solely on the external mutex. */
   atomic_bool loaded;
   asn1SccOBCP_Id id;
   asn1SccOBCP_Code code;
   /* Cross-thread fields written by PI functions (under the external mutex) and
    * read by the worker thread, or vice-versa.  C11 atomic types are used so
    * that acquire/release ordering emits the hardware barriers required on ARM
    * (ldar / stlr on ARMv8; lda / stl on ARMv7).  On x86 the operations
    * reduce to plain loads/stores with a compiler fence only (TSO provides the
    * hardware ordering for free). volatile alone cannot provide this guarantee
    * on weakly-ordered architectures such as ARM Cortex-A / RTEMS SMP QDP. */
   atomic_int  status;          /* asn1SccOBCP_Execution_Status */
   atomic_uint current_step;    /* OBCP_NO_STEP when no step is in progress */
   atomic_bool abort_requested; /* set true by PI_abort_obcp; read by worker */
   atomic_bool stop_requested;  /* set true by PI_stop_obcp;  read by worker */
   atomic_uint stop_at_step;    /* asn1SccOBCP_Step_Id: 0 = first endstep */
} OBCP_Procedure;

static OBCP_Procedure obcps[OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS] = {};
static uint32_t obcps_count = 0;

typedef struct
{
   bool registered;
   bool used;
   asn1SccPID pid;
   asn1SccOBCP_Id obcp_id;
   uintptr_t native_thread_handle;
   /* Union forces alignment to at least sizeof(uintptr_t), which is required
    * by the MicroPython GC (VERIFY_PTR asserts word-aligned pointers). */
   union {
      char     bytes[OBCP_MICROPYTHON_HEAP_SIZE];
      uintptr_t _align;
   } heap;
   uint8_t packet_buffer[OBCP_PACKET_BUFFER_SIZE];
} OBCP_Worker;

static OBCP_Worker workers[OBCP_MAXIMUM_NUMBER_OF_REGISTERED_OBCP_WORKERS] = {};
static uint32_t workers_count = 0;

/* ===================================================================
 * Per-channel packet inlet buffer
 * ===================================================================
 * Each channel holds at most one packet at a time.
 * TODO: this can be significantly improved if Hal provides
 * a better semaphore implementation with:
 * -timeouts
 * -initialization value (so a true semaphore instead of a mutex)
 * -release being a defined behaviour in a non-owner thread
 *    (true semaphore instead of a mutes)\
 * Optional signalling via events provided via Hal would be a help.
 * The current implementation is to demonstrate the working principle.
 * =================================================================== */

typedef struct
{
   asn1SccOBCP_Packet packet;
   /* Synchronises producer (PI_receive_packet) and consumer (wrapper_receive_packet).
    * Producer: store payload, then atomic_store(..., memory_order_release).
    * Consumer: atomic_load(..., memory_order_acquire), then read payload.
    * This acquire-release pair provides the necessary memory barrier on both
    * x86 (compiler fence) and ARM (stlr/ldar or stl/lda instructions). */
   atomic_bool occupied;
} OBCP_PacketChannel;

static OBCP_PacketChannel packet_channels[OBCP_PACKET_CHANNEL_COUNT];

static bool obcp_code_is_precompiled_mpy(const asn1SccOBCP_Code *code)
{
   return code->nCount >= 2 &&
          (uint8_t)code->arr[0] == OBCP_MPY_MAGIC_NUMBER &&
          (uint8_t)code->arr[1] == MPY_VERSION;
}

static inline int32_t get_worker_id_by_pid(const asn1SccPID pid)
{
   for (int32_t id = 0; id < (int32_t)workers_count; id++)
   {
      if (workers[id].pid == pid)
      {
         return id;
      }
   }
   return -1;
}

static inline void clear_obcp(const uint32_t id)
{
   /* Relaxed: clear_obcp is only called while the engine mutex is held (or
    * during single-threaded startup) and no concurrent worker can observe
    * the slot after it has been cleared. */
   atomic_store_explicit(&obcps[id].loaded, false, memory_order_relaxed);
   obcps[id].code.nCount = 0;
   /* Relaxed ordering is sufficient here: clear_obcp is only called while the
    * engine mutex is held (or during single-threaded startup), so no concurrent
    * reader can observe these stores out-of-order. */
   atomic_store_explicit(&obcps[id].status, OBCP_Execution_Status_inactive, memory_order_relaxed);
   atomic_store_explicit(&obcps[id].current_step, OBCP_NO_STEP, memory_order_relaxed);
   atomic_store_explicit(&obcps[id].abort_requested, false, memory_order_relaxed);
   atomic_store_explicit(&obcps[id].stop_requested, false, memory_order_relaxed);
   atomic_store_explicit(&obcps[id].stop_at_step, 0u, memory_order_relaxed);
}

static inline void clear_engine()
{
   obcps_count = 0;
   for (uint32_t i = 0; i < OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS; i++)
   {
      clear_obcp(i);
   }
   workers_count = 0;
   for (uint32_t i = 0; i < OBCP_MAXIMUM_NUMBER_OF_REGISTERED_OBCP_WORKERS; i++)
   {
      workers[i].registered = 0;
      workers[i].used = 0;
   }
}

/* ===================================================================
 * Wrapper functions to route obcpengine calls to TASTE RI functions
 * =================================================================== */

/* Returns the obcps[] index for the OBCP running in the calling thread,
 * or -1 if no OBCP index has been stored in TLS for this thread. */
static int32_t get_current_obcp_index_for_thread(void)
{
   return (int32_t)obcp_engine_tls_get(obcp_thread_local_value_index_obcp_index) - 1;
}

/* Raise a MicroPython exception if the current OBCP has been aborted.
 * Called at the entry of every user-facing wrapper. */
static void check_abort(void)
{
   const int32_t obcp_idx = get_current_obcp_index_for_thread();
   if (obcp_idx >= 0 && atomic_load_explicit(&obcps[obcp_idx].abort_requested, memory_order_acquire))
   {
      mp_raise_msg(&mp_type_Exception, MP_ERROR_TEXT("OBCP aborted"));
   }
}

/* Wrapper for beginstep: record that step `id` has started. */
static bool wrapper_beginstep(const uint32_t id)
{
   check_abort();
   const int32_t obcp_idx = get_current_obcp_index_for_thread();
   if (obcp_idx < 0)
   {
      return false;
   }
   /* Release: ensures PI_get_obcp_status (acquire) sees the updated step id. */
   atomic_store_explicit(&obcps[obcp_idx].current_step, id, memory_order_release);
   return true;
}

/* Wrapper for endstep: verify `id` matches the begun step, then clear it.
 * Returns false (causing a MicroPython RuntimeError) on mismatch. */
static bool wrapper_endstep(const uint32_t id, const bool success)
{
   check_abort();
   (void)success; /* success is informational; mismatch is the only hard error */
   const int32_t obcp_idx = get_current_obcp_index_for_thread();
   if (obcp_idx < 0)
   {
      return false;
   }
   /* Relaxed: same thread wrote current_step in wrapper_beginstep. */
   if (atomic_load_explicit(&obcps[obcp_idx].current_step, memory_order_relaxed) != id)
   {
      return false;
   }
   /* Release: ensures PI_get_obcp_status (acquire) sees OBCP_NO_STEP. */
   atomic_store_explicit(&obcps[obcp_idx].current_step, OBCP_NO_STEP, memory_order_release);
   /* Acquire on stop_requested: pairs with the release store in PI_stop_obcp,
    * guaranteeing that stop_at_step is visible before we read it below.
    * stop_at_step is read once into a local variable to avoid a TOCTOU
    * race: PI_stop_obcp (Protected) can overwrite stop_at_step between two
    * separate relaxed loads, producing inconsistent stop-at logic. */
   if (atomic_load_explicit(&obcps[obcp_idx].stop_requested, memory_order_acquire))
   {
      const uint32_t step_to_stop_at = atomic_load_explicit(&obcps[obcp_idx].stop_at_step, memory_order_relaxed);
      if (step_to_stop_at == 0u || step_to_stop_at == id)
      {
         mp_raise_msg(&mp_type_Exception, MP_ERROR_TEXT("OBCP stopped"));
      }
   }
   return true;
}

/* Wrapper for send_event */
static void wrapper_send_event(const uint32_t event_id)
{
   check_abort();
   asn1SccOBCP_Event_Id id = event_id;
   obcp_engine_RI_send_event(&id);
}

/* Wrapper for output_message */
static bool wrapper_output_message(const char *text, size_t length)
{
   check_abort();
   asn1SccOBCP_Text msg;
   const uint32_t max_length = (uint32_t)(sizeof(asn1SccOBCP_Text) - 1); // -1 accounts for null terminator
   /* Ensure we don't overflow the buffer */
   size_t copy_len = (length < max_length) ? length : max_length;
   memcpy(msg, text, copy_len);
   msg[copy_len] = '\0';
   obcp_engine_RI_output_message(&msg);
   return true;
}

/* Wrapper for get_current_time */
static bool wrapper_get_current_time(uint32_t *seconds, uint32_t *milliseconds)
{
   check_abort();
   asn1SccT_Int32 sec, msec;
   obcp_engine_RI_get_current_time(&sec, &msec);
   *seconds = (uint32_t)sec;
   *milliseconds = (uint32_t)msec;
   return true;
}

/* Wrapper for wait (relative delay in milliseconds) */
static bool wrapper_wait(const uint32_t milliseconds)
{
   check_abort();
   return Hal_SleepNs((uint64_t)milliseconds * NS_PER_MS);
}

/* Wrapper for waituntil (absolute time in seconds + milliseconds) */
static bool wrapper_waituntil(const uint32_t target_seconds, const uint32_t target_milliseconds)
{
   check_abort();
   const uint64_t target_ns = ((uint64_t)target_seconds * MS_PER_SECOND + target_milliseconds) * NS_PER_MS;
   const uint64_t now_ns    = Hal_GetElapsedTimeInNs();
   if (target_ns <= now_ns)
   {
      return true;
   }
   return Hal_SleepNs(target_ns - now_ns);
}

/* Wrapper for read_int_parameter */
static bool wrapper_read_int_parameter(const uint32_t id, int32_t *value)
{
   check_abort();
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Type param_type = OBCP_Parameter_Type_integer_type;
   asn1SccOBCP_Parameter_Value param_value;

   obcp_engine_RI_get_parameter_value(&param_id, &param_type, &param_value);

   if (param_value.kind == OBCP_Parameter_Value_int_value_PRESENT)
   {
      *value = (int32_t)param_value.u.int_value;
      return true;
   }
   return false;
}

/* Wrapper for write_int_parameter */
static bool wrapper_write_int_parameter(const uint32_t id, const int32_t value)
{
   check_abort();
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Value param_value;
   param_value.kind = OBCP_Parameter_Value_int_value_PRESENT;
   param_value.u.int_value = (asn1SccT_Int32)value;

   obcp_engine_RI_set_parameter_value(&param_id, &param_value);
   return true;
}


/* Wrapper for read_enum_parameter */
static bool wrapper_read_enum_parameter(const uint32_t id, int32_t *value)
{
   check_abort();
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Type param_type = OBCP_Parameter_Type_enumerated_type;
   asn1SccOBCP_Parameter_Value param_value;

   obcp_engine_RI_get_parameter_value(&param_id, &param_type, &param_value);

   if (param_value.kind == OBCP_Parameter_Value_enum_value_PRESENT)
   {
      *value = (int32_t)param_value.u.enum_value;
      return true;
   }
   return false;
}

/* Wrapper for write_enum_parameter */
static bool wrapper_write_enum_parameter(const uint32_t id, const int32_t value)
{
   check_abort();
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Value param_value;
   param_value.kind = OBCP_Parameter_Value_enum_value_PRESENT;
   param_value.u.enum_value = (asn1SccT_Int32)value;

   obcp_engine_RI_set_parameter_value(&param_id, &param_value);
   return true;
}

/* Wrapper for read_float_parameter */
static bool wrapper_read_float_parameter(const uint32_t id, float *value)
{
   check_abort();
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Type param_type = OBCP_Parameter_Type_float_type;
   asn1SccOBCP_Parameter_Value param_value;

   obcp_engine_RI_get_parameter_value(&param_id, &param_type, &param_value);

   if (param_value.kind == OBCP_Parameter_Value_float_value_PRESENT)
   {
      *value = (float)param_value.u.float_value;
      return true;
   }
   return false;
}

/* Wrapper for write_float_parameter */
static bool wrapper_write_float_parameter(const uint32_t id, const float value)
{
   check_abort();
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Value param_value;
   param_value.kind = OBCP_Parameter_Value_float_value_PRESENT;
   param_value.u.float_value = (asn1SccT_Float32)value;

   obcp_engine_RI_set_parameter_value(&param_id, &param_value);
   return true;
}

/* Wrapper for read_bool_parameter */
static bool wrapper_read_bool_parameter(const uint32_t id, bool *value)
{
   check_abort();
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Type param_type = OBCP_Parameter_Type_boolean_type;
   asn1SccOBCP_Parameter_Value param_value;

   obcp_engine_RI_get_parameter_value(&param_id, &param_type, &param_value);

   if (param_value.kind == OBCP_Parameter_Value_bool_value_PRESENT)
   {
      *value = (bool)param_value.u.bool_value;
      return true;
   }
   return false;
}

/* Wrapper for write_bool_parameter */
static bool wrapper_write_bool_parameter(const uint32_t id, const bool value)
{
   check_abort();
   asn1SccOBCP_Parameter_Id param_id = id;
   asn1SccOBCP_Parameter_Value param_value;
   param_value.kind = OBCP_Parameter_Value_bool_value_PRESENT;
   param_value.u.bool_value = (asn1SccT_Boolean)value;

   obcp_engine_RI_set_parameter_value(&param_id, &param_value);
   return true;
}

/* ===================================================================
 * Packet wrapper functions
 * =================================================================== */

/* Returns true when a packet is buffered on the given channel. */
static bool wrapper_is_packet_available(const uint32_t channel)
{
   check_abort();
   if (channel >= OBCP_PACKET_CHANNEL_COUNT)
   {
      return false;
   }
   return atomic_load_explicit(&packet_channels[channel].occupied, memory_order_acquire);
}

/* Returns the index of the first channel that currently has a packet,
 * or false when none do. */
static bool wrapper_get_channel_with_packet_available(uint32_t *channel)
{
   check_abort();
   for (uint32_t i = 0; i < OBCP_PACKET_CHANNEL_COUNT; ++i)
   {
      if (atomic_load_explicit(&packet_channels[i].occupied, memory_order_acquire))
      {
         *channel = i;
         return true;
      }
   }
   return false;
}

/* Output path: packets are always forwarded directly to the TASTE RI,
 * so a valid channel can always accept a send request. */
static bool wrapper_can_send_packet(const uint32_t channel)
{
   check_abort();
   return channel < OBCP_PACKET_CHANNEL_COUNT;
}

/* Forward the packet to the TASTE harness via the send_packet RI. */
static bool wrapper_send_packet(const uint32_t channel,
                                const uint32_t length,
                                const char *const data)
{
   check_abort();
   asn1SccOBCP_Channel_Id ch_id  = (asn1SccOBCP_Channel_Id)channel;
   asn1SccOBCP_Packet     packet;
   asn1SccT_Boolean       success = FALSE;

   uint32_t copy_len = length;
   assert(copy_len <= (uint32_t)sizeof(packet.arr));
   // Guard against an unwanted crash, as a truncated packet is preferrable to app death.
   // Incorrect length should be found during testing using the assert.
   if (copy_len > (uint32_t)sizeof(packet.arr))
   {
      copy_len = (uint32_t)sizeof(packet.arr);
   }
   memcpy(packet.arr, data, copy_len);
   packet.nCount = (int)copy_len;

   obcp_engine_RI_send_packet(&ch_id, &packet, &success);
   return (bool)success;
}

/* Receive a packet from the inlet buffer.
 *
 * timeout_milliseconds == 0 : non-blocking check.
 * 0 < timeout_milliseconds : poll with Hal_SleepNs until a packet arrives or the deadline is exceeded.
 */
static bool wrapper_receive_packet(const uint32_t channel,
                                   uint32_t *length,
                                   char *data,
                                   uint32_t timeout_milliseconds)
{
   check_abort();
   if (channel >= OBCP_PACKET_CHANNEL_COUNT)
   {
      return false;
   }

   OBCP_PacketChannel *ch = &packet_channels[channel];

   if (timeout_milliseconds == 0U)
   {
      /* Non-blocking: return immediately if no packet is present. */
      if (!atomic_load_explicit(&ch->occupied, memory_order_acquire))
      {
         return false;
      }
   }
   else
   {
      /* Timed wait: poll at PACKET_POLL_INTERVAL_NS intervals. */
      const uint64_t deadline_ns =
          Hal_GetElapsedTimeInNs() +
          (uint64_t)timeout_milliseconds * NS_PER_MS;

      while (!atomic_load_explicit(&ch->occupied, memory_order_acquire))
      {
         check_abort();
         if (Hal_GetElapsedTimeInNs() >= deadline_ns)
         {
            return false;
         }
         Hal_SleepNs(PACKET_POLL_INTERVAL_NS);
      }
   }

   /* mp_raise_msg does not return, but just in case, ensure that false is returned without raising
      compiler warnings about dead code. */
   bool result = false;
   /* Consume the buffered packet. */
   uint32_t copy_len = (uint32_t)ch->packet.nCount;
   if (*length < copy_len)
   {
      /* Release the channel before raising: without this the channel would
       * remain permanently occupied after the exception unwinds the stack. */
      atomic_store_explicit(&ch->occupied, false, memory_order_release);
      mp_raise_msg(&mp_type_ValueError, MP_ERROR_TEXT("Receive buffer too small"));
   }
   else
   {
      memcpy(data, ch->packet.arr, copy_len);
      *length = copy_len;
      /* Release the channel only after the payload has been fully consumed.
       * The release store pairs with the acquire load in PI_receive_packet,
       * ensuring the slot is not reused before we finish reading. */
      atomic_store_explicit(&ch->occupied, false, memory_order_release);
      result = true;
   }

   return result;
}

/* Compare two OBCP ids without relying on null termination. */
static bool isObcpIdEqual(const asn1SccOBCP_Id id1, const asn1SccOBCP_Id id2)
{
   size_t n = sizeof(asn1SccOBCP_Id);
   for (size_t i = 0; i < n; ++i)
   {
      if (id1[i] != id2[i])
      {
         return false;
      }
   }
   return true;
}

/* Return index into `obcps` array for given id, or -1 if not found. */
static int32_t getObcpIndex(const asn1SccOBCP_Id id)
{
   for (uint32_t i = 0; i < OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS; ++i)
   {
      /* Relaxed: getObcpIndex is only called from Protected PIs; the
       * component mutex provides ordering among all Protected callers. */
      if (atomic_load_explicit(&obcps[i].loaded, memory_order_relaxed) && isObcpIdEqual(obcps[i].id, id))
      {
         return (int32_t)i;
      }
   }
   return -1;
}

void obcp_engine_startup(void)
{
   obcp_engine_tls_init();
   clear_engine();

   /* Initialise per-channel packet inlet buffers and their semaphores. */
   for (uint32_t i = 0; i < OBCP_PACKET_CHANNEL_COUNT; ++i)
   {
      atomic_init(&packet_channels[i].occupied, false);
   }

   /* Initialize obcpengine with callbacks to TASTE RI functions */
   obcp_engine_context_t context = {
       .obcp_engine_get_thread_local_value = obcp_engine_tls_get,
       .obcp_engine_set_thread_local_value = obcp_engine_tls_set,
       .obcp_read_int_parameter = wrapper_read_int_parameter,
       .obcp_write_int_parameter = wrapper_write_int_parameter,
       .obcp_read_enum_parameter = wrapper_read_enum_parameter,
       .obcp_write_enum_parameter = wrapper_write_enum_parameter,
       .obcp_read_float_parameter = wrapper_read_float_parameter,
       .obcp_write_float_parameter = wrapper_write_float_parameter,
       .obcp_read_bool_parameter = wrapper_read_bool_parameter,
       .obcp_write_bool_parameter = wrapper_write_bool_parameter,
       .obcp_send_event = wrapper_send_event,
       .obcp_write = wrapper_output_message,
       .obcp_beginstep = wrapper_beginstep,
       .obcp_endstep = wrapper_endstep,
       .obcp_wait = wrapper_wait,
       .obcp_waituntil = wrapper_waituntil,
       .obcp_gettime = wrapper_get_current_time,
       .obcp_is_packet_available = wrapper_is_packet_available,
       .obcp_get_channel_with_packet_available = wrapper_get_channel_with_packet_available,
       .obcp_can_send_packet = wrapper_can_send_packet,
       .obcp_send_packet = wrapper_send_packet,
       .obcp_receive_packet = wrapper_receive_packet
   };

   obcpengine_init(&context);
}

/* Protected PI (interfaceview.xml kind="Protected"): serialised by the obcp_engine component mutex. */
void obcp_engine_PI_abort_obcp(const asn1SccOBCP_Id *IN_id,
                               asn1SccT_Boolean *OUT_success)

{
   *OUT_success = FALSE;
   const int32_t index = getObcpIndex(*IN_id);
   if (index < 0)
   {
      return;
   }
   /* Acquire on status: pairs with the release store in PI_do_work, ensuring
    * the worker's full initialisation is visible before we flag it for abort. */
   if (atomic_load_explicit(&obcps[index].status, memory_order_acquire) == OBCP_Execution_Status_active_and_running)
   {
      /* Release: worker's acquire in check_abort() makes this visible promptly. */
      atomic_store_explicit(&obcps[index].abort_requested, true, memory_order_release);
      *OUT_success = TRUE;
   }
}

extern void obcp_engine_RI_activate_worker_To_PID(asn1SccPID dest_pid, const asn1SccT_Int32 *IN_obcp_index);

/* Protected PI (interfaceview.xml kind="Protected"): serialised by the obcp_engine component mutex. */
void obcp_engine_PI_activate_obcp(const asn1SccOBCP_Id *IN_id,
                                  asn1SccT_Boolean *OUT_success)

{
   *OUT_success = FALSE;

   asn1SccT_Boolean can_activate = FALSE;
   obcp_engine_PI_can_obcp_be_activated(IN_id, &can_activate);
   if (!can_activate)
   {
      return;
   }

   const int32_t obcp_index = getObcpIndex(*IN_id);
   if (obcp_index < 0)
   {
      return;
   }

   for (uint32_t i = 0; i < workers_count; ++i)
   {
      if (workers[i].registered && !workers[i].used)
      {
         workers[i].used = true;
         memcpy(workers[i].obcp_id, *IN_id, sizeof(asn1SccOBCP_Id));

         asn1SccT_Int32 idx = (asn1SccT_Int32)obcp_index;

         DEBUG_PRINT("Sending ACTIVATE to Worker[%d] PID %d\n", i, workers[i].pid);
         obcp_engine_RI_activate_worker_To_PID(workers[i].pid, &idx);

         *OUT_success = TRUE;
         return;
      }
   }
}

/* Protected PI (interfaceview.xml kind="Protected"): serialised by the obcp_engine component mutex. */
void obcp_engine_PI_can_obcp_be_activated(const asn1SccOBCP_Id *IN_id,
                                          asn1SccT_Boolean *OUT_success)

{
   *OUT_success = FALSE;

   if (getObcpIndex(*IN_id) < 0)
   {
      return;
   }

   for (uint32_t i = 0; i < workers_count; ++i)
   {
      if (workers[i].registered && !workers[i].used)
      {
         *OUT_success = TRUE;
         return;
      }
   }
}

/* Protected PI (interfaceview.xml kind="Protected"): serialised by the obcp_engine component mutex. */
void obcp_engine_PI_can_obcp_be_loaded(const asn1SccOBCP_Id *IN_id,
                                       asn1SccT_Boolean *OUT_success)

{
   *OUT_success = FALSE;

   if (obcps_count >= OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS)
   {
      return;
   }

   if (getObcpIndex(*IN_id) >= 0)
   {
      return;
   }

   *OUT_success = TRUE;
}

/* Protected PI (interfaceview.xml kind="Protected"): serialised by the obcp_engine component mutex. */
void obcp_engine_PI_get_obcp_status(const asn1SccOBCP_Id *IN_id,
                                    asn1SccOBCP_Execution_Status *OUT_execution_status,
                                    asn1SccOBCP_Step_Id *OUT_step_id,
                                    asn1SccT_Boolean *OUT_success)

{
   *OUT_success = FALSE;
   const int32_t index = getObcpIndex(*IN_id);
   if (index < 0)
   {
      return;
   }
   /* Acquire: pairs with release stores in PI_do_work (status) and
    * wrapper_beginstep / wrapper_endstep (current_step). */
   *OUT_execution_status = (asn1SccOBCP_Execution_Status)atomic_load_explicit(&obcps[index].status, memory_order_acquire);
   *OUT_step_id          = (asn1SccOBCP_Step_Id)atomic_load_explicit(&obcps[index].current_step, memory_order_acquire);
   *OUT_success = TRUE;
}

/* Protected PI (interfaceview.xml kind="Protected"): serialised by the obcp_engine component mutex. */
void obcp_engine_PI_load_obcp(const asn1SccOBCP_Id *IN_id,
                              const asn1SccOBCP_Code *IN_code,
                              asn1SccT_Boolean *OUT_success)

{
   *OUT_success = FALSE;

   asn1SccT_Boolean can_load = FALSE;
   obcp_engine_PI_can_obcp_be_loaded(IN_id, &can_load);
   if (!can_load)
   {
      return;
   }

   for (uint32_t id = 0; id < OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS; ++id)
   {
      /* Relaxed: under the Protected mutex; no concurrent worker can see this slot yet. */
      if (!atomic_load_explicit(&obcps[id].loaded, memory_order_relaxed))
      {
         memcpy(obcps[id].id, *IN_id, sizeof(asn1SccOBCP_Id));
         memcpy(obcps[id].code.arr, IN_code->arr, IN_code->nCount);
         obcps[id].code.nCount = IN_code->nCount;
         /* Relaxed: the OBCP slot is not yet visible to worker threads; the
          * subsequent mutex release by the caller provides the required fence. */
         atomic_store_explicit(&obcps[id].status, OBCP_Execution_Status_inactive, memory_order_relaxed);
         atomic_store_explicit(&obcps[id].current_step, OBCP_NO_STEP, memory_order_relaxed);
         atomic_store_explicit(&obcps[id].abort_requested, false, memory_order_relaxed);
         atomic_store_explicit(&obcps[id].stop_requested, false, memory_order_relaxed);
         atomic_store_explicit(&obcps[id].stop_at_step, 0u, memory_order_relaxed);
         /* Release: pairs with the acquire load in PI_do_work.  All preceding
          * writes (code.arr, code.nCount, id, and the atomic flag resets)
          * are formally ordered before this store, guaranteeing that the
          * worker sees the complete code buffer when it reads loaded == true. */
         atomic_store_explicit(&obcps[id].loaded, true, memory_order_release);
         ++obcps_count;
         *OUT_success = TRUE;
         return;
      }
   }
}

/* Protected PI (interfaceview.xml kind="Protected"): serialised by the obcp_engine component mutex. */
void obcp_engine_PI_receive_packet( const asn1SccOBCP_Channel_Id *IN_channel,
   const asn1SccOBCP_Packet *IN_packet,
   asn1SccT_Boolean *OUT_success)
{
   const uint32_t ch_idx = (uint32_t)*IN_channel;
   if (ch_idx >= OBCP_PACKET_CHANNEL_COUNT)
   {
      *OUT_success = FALSE;
      return;
   }

   OBCP_PacketChannel *ch = &packet_channels[ch_idx];

   /* Do not wait if busy, just return; a busy loop can be implemented
      on the user-side. Just blocking here would block ALL reception
      channels, which is undesired */
   if (atomic_load_explicit(&ch->occupied, memory_order_acquire))
   {
      *OUT_success = FALSE;
      return;
   }

   /* Write the payload before publishing the flag. The release store
    * pairs with every acquire load in the wrapper functions, guaranteeing
    * that the complete packet is visible before the consumer sees
    * occupied == true (required on ARM; a compiler fence on x86). */
   ch->packet = *IN_packet;
   atomic_store_explicit(&ch->occupied, true, memory_order_release);
   *OUT_success = TRUE;
}

/* Protected PI (interfaceview.xml kind="Protected"): serialised by the obcp_engine component mutex. */
void obcp_engine_PI_start_obcp_engine(void)
{
   clear_engine();
   obcp_engine_RI_initiate_registration();
}

/* Protected PI (interfaceview.xml kind="Protected"): serialised by the obcp_engine component mutex. */
void obcp_engine_PI_stop_obcp( const asn1SccOBCP_Id *IN_id,
   const asn1SccOBCP_Step_Id *IN_step_id,
   asn1SccT_Boolean *OUT_success)
{
   *OUT_success = FALSE;
   const int32_t index = getObcpIndex(*IN_id);
   if (index < 0)
   {
      return;
   }
   if (atomic_load_explicit(&obcps[index].status, memory_order_acquire) == OBCP_Execution_Status_active_and_running)
   {
      /* Write stop_at_step BEFORE publishing stop_requested. The release store
       * on stop_requested pairs with the acquire load in wrapper_endstep,
       * guaranteeing stop_at_step is visible to the worker before it reads it. */
      atomic_store_explicit(&obcps[index].stop_at_step, (uint32_t)*IN_step_id, memory_order_relaxed);
      atomic_store_explicit(&obcps[index].stop_requested, true, memory_order_release);
      *OUT_success = TRUE;
   }
}

/* Protected PI (interfaceview.xml kind="Protected"): serialised by the obcp_engine component mutex. */
/* This function blocks until all OBCPS are inactive by design */
void obcp_engine_PI_stop_obcp_engine(void)
{
   bool waiting_for_obcps = false;

   for (uint32_t i = 0; i < OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS; ++i)
   {
      /* Relaxed: PI_stop_obcp_engine holds the Protected mutex. */
      if (!atomic_load_explicit(&obcps[i].loaded, memory_order_relaxed))
      {
         continue;
      }

      if (atomic_load_explicit(&obcps[i].status, memory_order_acquire) == OBCP_Execution_Status_active_and_running)
      {
         atomic_store_explicit(&obcps[i].abort_requested, true, memory_order_release);
      }
   }

   do
   {
      waiting_for_obcps = false;

      for (uint32_t i = 0; i < OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS; ++i)
      {
         /* Acquire: pairs with the release store on status in PI_do_work,
          * ensuring the worker's full cleanup is visible before we exit. */
         /* Relaxed on loaded: under the Protected mutex. */
         if (atomic_load_explicit(&obcps[i].loaded, memory_order_relaxed) && atomic_load_explicit(&obcps[i].status, memory_order_acquire) != OBCP_Execution_Status_inactive)
         {
            waiting_for_obcps = true;
            break;
         }
      }

      if (waiting_for_obcps)
      {
         Hal_SleepNs(PACKET_POLL_INTERVAL_NS);
      }
   } while (waiting_for_obcps);

   clear_engine();
}

/* Protected PI (interfaceview.xml kind="Protected"): serialised by the obcp_engine component mutex. */
void obcp_engine_PI_unload_obcp(const asn1SccOBCP_Id *IN_id,
                                asn1SccT_Boolean *OUT_success)

{
   *OUT_success = FALSE;

   const int32_t index = getObcpIndex(*IN_id);
   if (index < 0)
   {
      return;
   }

   if (atomic_load_explicit(&obcps[index].status, memory_order_acquire) != OBCP_Execution_Status_inactive)
   {
      return;
   }

   clear_obcp(index);
   if (obcps_count > 0)
   {
      // Defensive programming pattern to guard against state inconsistency
      --obcps_count;
   }
   *OUT_success = TRUE;
}

extern asn1SccPID obcp_engine_do_work_get_sender();

/* Unprotected PI (interfaceview.xml kind="Unprotected"): NOT serialised by the component mutex; concurrent invocations are possible. */
/* Function should be called by a worker, in it's own thread, in response to a obcp_engine_RI_activate_worker call
   After completing it, the worker, in the same thread, shall call obcp_engine_PI_release_worker.
   By design, there are multiple workers calling this function concurrently, each with a different OBCP and worker ID */
void obcp_engine_PI_do_work(const asn1SccT_Int32 *obcp_index)
{
   const uint32_t idx = (uint32_t)(*obcp_index);
   const asn1SccPID pid = obcp_engine_do_work_get_sender();
   const int32_t worker_id = get_worker_id_by_pid(pid);

   /* Acquire: pairs with the release store in PI_load_obcp, ensuring that
    * code.arr and code.nCount are visible once loaded == true is observed. */
   if (idx >= OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS || !atomic_load_explicit(&obcps[idx].loaded, memory_order_acquire))
   {
      if (worker_id >= 0)
      {
         // If worker ID is correct, release it.
         workers[worker_id].used = false;
      }
      return;
   }

   if (worker_id < 0)
   {
      DEBUG_PRINT("DO WORK: unknown worker PID %d — aborting\n", pid);
      /* Release: stop_obcp_engine polls status with acquire; ensure it sees inactive. */
      atomic_store_explicit(&obcps[idx].status, OBCP_Execution_Status_inactive, memory_order_release);
      return;
   }

   /* Bind this thread's TLS slot on every do_work entry.  On Linux this is a
    * no-op; on RTEMS/FreeRTOS it is idempotent after the first call. */
   obcp_engine_tls_bind();
   /* Release: PI_abort_obcp and PI_stop_obcp read status with acquire; the
    * release here ensures their acquire sees active_and_running only after
    * TLS is fully bound and the worker is genuinely ready to execute. */
   atomic_store_explicit(&obcps[idx].status, OBCP_Execution_Status_active_and_running, memory_order_release);


   DEBUG_PRINT("DO WORK Worker[%d] PID %d\n", worker_id, pid);

   /* Store the obcps[] index in TLS (offset by +1 so 0 means "none"). */
   obcp_engine_tls_set(obcp_thread_local_value_index_obcp_index, (uintptr_t)(idx + 1u));

   obcpengine_provide_buffer(workers[worker_id].packet_buffer,
                             OBCP_PACKET_BUFFER_SIZE);

   if (obcp_code_is_precompiled_mpy(&obcps[idx].code))
   {
      obcpengine_execute_mpy(
         (const uint8_t *)obcps[idx].code.arr,
         (size_t)obcps[idx].code.nCount,
         workers[worker_id].heap.bytes,
         OBCP_MICROPYTHON_HEAP_SIZE);
   }
   else
   {
      obcpengine_execute_py(
         (const char *)obcps[idx].code.arr,
         workers[worker_id].heap.bytes,
         OBCP_MICROPYTHON_HEAP_SIZE);
   }

   workers[worker_id].native_thread_handle = 0;
   obcp_engine_tls_set(obcp_thread_local_value_index_obcp_index, 0u);
   /* Relaxed for the flag resets: no concurrent reader exists at this point
    * (the OBCP has finished executing) so no cross-thread ordering is needed. */
   atomic_store_explicit(&obcps[idx].abort_requested, false, memory_order_relaxed);
   atomic_store_explicit(&obcps[idx].stop_requested,  false, memory_order_relaxed);
   atomic_store_explicit(&obcps[idx].stop_at_step,    0u,    memory_order_relaxed);
   /* Release on status: stop_obcp_engine polls with acquire and must see
    * inactive only after all cleanup stores above are globally visible. */
   atomic_store_explicit(&obcps[idx].status, OBCP_Execution_Status_inactive, memory_order_release);
}

extern asn1SccPID obcp_engine_release_worker_get_sender();

/* Protected PI (interfaceview.xml kind="Protected"): serialised by the obcp_engine component mutex. */
void obcp_engine_PI_release_worker(void)
{
   const asn1SccPID pid = obcp_engine_release_worker_get_sender();
   const int32_t id = get_worker_id_by_pid(pid);
   if (id >= 0)
   {
      workers[id].used = false;
   }
   DEBUG_PRINT("RELEASE Worker[%d] PID %d\n", id, pid);
}

extern asn1SccPID obcp_engine_register_worker_get_sender();

/* Unprotected PI (interfaceview.xml kind="Unprotected"): NOT serialised by the component mutex; concurrent invocations are possible. */
/* Function is unprotected, as it is used as a callback in response to obcp_engine_RI_initiate_registration
   which is called in obcp_engine_PI_start_obcp_engine, itself protected by the component-wide mutex,
   which is non-reentrant. */
void obcp_engine_PI_register_worker()
{
   if (workers_count >= OBCP_MAXIMUM_NUMBER_OF_REGISTERED_OBCP_WORKERS)
   {
      return;
   }
   const uint32_t id = workers_count++;
   const asn1SccPID pid = obcp_engine_register_worker_get_sender();

   workers[id].pid = pid;
   workers[id].registered = true;
   workers[id].used = false;

   DEBUG_PRINT("REGISTERED Worker[%d] as PID %d\n", id, pid);
}