/* Body file for function harness
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "harness.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <signal.h>
#include <unistd.h>


void harness_startup(void)
{
   // NOP
}

void harness_PI_get_current_time
      (asn1SccT_Int32 *OUT_seconds,
       asn1SccT_Int32 *OUT_milliseconds)

{
   // TODO
}


/* -----------------------------------------------------------------------
 * In-memory parameter store (supports up to PARAM_STORE_SIZE parameters)
 * ----------------------------------------------------------------------- */

#define PARAM_STORE_SIZE 16

typedef struct {
   asn1SccOBCP_Parameter_Id    id;
   asn1SccOBCP_Parameter_Value value;
   bool                        valid;
} Harness_ParamEntry;

static Harness_ParamEntry param_store[PARAM_STORE_SIZE];

/* ----------------------------------------------------------------------- */

void harness_PI_get_parameter_value
      (const asn1SccOBCP_Parameter_Id *IN_id,
       const asn1SccOBCP_Parameter_Type *IN_parameter_type,
       asn1SccOBCP_Parameter_Value *OUT_parameter_value)

{
   for (int i = 0; i < PARAM_STORE_SIZE; i++) {
      if (param_store[i].valid && param_store[i].id == *IN_id) {
         *OUT_parameter_value = param_store[i].value;
         return;
      }
   }
   /* Parameter not found: return a default zero integer value */
   OUT_parameter_value->kind        = OBCP_Parameter_Value_int_value_PRESENT;
   OUT_parameter_value->u.int_value = 0;
}


/* -----------------------------------------------------------------------
 * IO write test verification
 * ----------------------------------------------------------------------- */

static const char * const io_test_expected[] = {
   "IO test: single-line write\n",
   "IO test: numeric value: 42\n",
   "IO test: string concatenation\n",
};
#define IO_TEST_EXPECTED_COUNT \
   (sizeof(io_test_expected) / sizeof(io_test_expected[0]))

static size_t io_test_msg_index  = 0;
static bool   io_write_test_active = false;

/* ----------------------------------------------------------------------- */

void harness_PI_output_message
      (const asn1SccOBCP_Text *IN_text)

{
   printf("%s", *IN_text);

   if (io_write_test_active) {
      if (io_test_msg_index >= IO_TEST_EXPECTED_COUNT) {
         printf("IO test ERROR: unexpected extra message: \"%s\"\n", *IN_text);
      } else if (strcmp(*IN_text, io_test_expected[io_test_msg_index]) != 0) {
         printf("IO test ERROR: message %zu: expected \"%s\", got \"%s\"\n",
                io_test_msg_index,
                io_test_expected[io_test_msg_index],
                *IN_text);
      }
      io_test_msg_index++;
   }
}


void harness_PI_send_packet
      (const asn1SccOBCP_Channel_Id *IN_channel,
       const asn1SccOBCP_Packet *IN_packet,
       asn1SccT_Boolean *OUT_success)

{
   // TODO
}


void harness_PI_set_parameter_value
      (const asn1SccOBCP_Parameter_Id *IN_id,
       const asn1SccOBCP_Parameter_Value *IN_parameter_value)

{
   int empty = -1;
   for (int i = 0; i < PARAM_STORE_SIZE; i++) {
      if (param_store[i].valid && param_store[i].id == *IN_id) {
         param_store[i].value = *IN_parameter_value;
         return;
      }
      if (!param_store[i].valid && empty < 0) {
         empty = i;
      }
   }
   if (empty >= 0) {
      param_store[empty].id    = *IN_id;
      param_store[empty].value = *IN_parameter_value;
      param_store[empty].valid = true;
   }
}


/* -----------------------------------------------------------------------
 * Harness OBCP definitions
 * ----------------------------------------------------------------------- */

typedef struct {
   asn1SccOBCP_Id   id;
   const char      *src;
} Harness_ObcpDef;

/* IO write test OBCP: exercises the obcpio.write function by sending
 * plain text, numeric conversions and string concatenation to the output.
 */
static const Harness_ObcpDef OBCP_IOTEST = {
   .id  = {'I','O','T','S','T'},
   .src =
      "import obcpio\n"
      "obcpio.write('IO test: single-line write\\n')\n"
      "obcpio.write('IO test: numeric value: ' + str(42) + '\\n')\n"
      "obcpio.write('IO test: ' + 'string ' + 'concatenation\\n')\n"
};

/* Datapool test OBCP: exercises write and read of int, enum, float and bool
 * parameters using the MicroPython obcpdatapool module.  Parameter IDs:
 *   1 = integer   2 = enum   3 = float   4 = bool
 */
static const Harness_ObcpDef OBCP_DPTEST = {
   .id  = {'D','P','T','S','T'},
   .src =
      "import obcpdatapool\n"
      "import obcpio\n"
      "obcpdatapool.writeintparameter(1, -42)\n"
      "v = obcpdatapool.readintparameter(1)\n"
      "if v != -42: raise RuntimeError('int fail')\n"
      "obcpio.write('DP int OK: ' + str(v) + '\\n')\n"
      "obcpdatapool.writeenumparameter(2, 7)\n"
      "v = obcpdatapool.readenumparameter(2)\n"
      "if v != 7: raise RuntimeError('enum fail')\n"
      "obcpio.write('DP enum OK: ' + str(v) + '\\n')\n"
      "obcpdatapool.writefloatparameter(3, 2.718)\n"
      "v = obcpdatapool.readfloatparameter(3)\n"
      "obcpio.write('DP float OK: ' + str(v) + '\\n')\n"
      "obcpdatapool.writeboolparameter(4, True)\n"
      "v = obcpdatapool.readboolparameter(4)\n"
      "if not v: raise RuntimeError('bool fail')\n"
      "obcpio.write('DP bool OK: ' + str(v) + '\\n')\n"
};

static const Harness_ObcpDef OBCP_TEST1 = {
   .id  = {'T','E','S','T','1'},
   .src = "import obcptime\nobcptime.wait(3000)\n"
};

static const Harness_ObcpDef OBCP_TEST2 = {
   .id  = {'T','E','S','T','2'},
   .src = "import obcptime\nobcptime.wait(5000)\n"
};

static const Harness_ObcpDef OBCP_TEST3 = {
   .id  = {'T','E','S','T','3'},
   .src = "import obcptime\nobcptime.wait(3000)\n"
};

/* -----------------------------------------------------------------------
 * Helpers
 * ----------------------------------------------------------------------- */

static bool load_obcp(const Harness_ObcpDef *def)
{
   asn1SccOBCP_Code code;
   const size_t len = strlen(def->src) + 1;
   memcpy(code.arr, def->src, len);
   code.nCount = (int)len;

   asn1SccT_Boolean ok = FALSE;
   harness_RI_load_obcp(&def->id, &code, &ok);
   if (!ok) {
      printf("Could not load OBCP %.5s\n", def->id);
   }
   return (bool)ok;
}

static bool activate_obcp(const Harness_ObcpDef *def)
{
   asn1SccT_Boolean ok = FALSE;
   harness_RI_activate_obcp(&def->id, &ok);
   if (!ok) {
      printf("Could not activate OBCP %.5s\n", def->id);
   }
   return (bool)ok;
}

static asn1SccOBCP_Execution_Status get_status(const Harness_ObcpDef *def)
{
   asn1SccOBCP_Execution_Status status = OBCP_Execution_Status_inactive;
   asn1SccT_Boolean ok = FALSE;
   harness_RI_get_obcp_status(&def->id, &status, &ok);
   if (!ok) {
      printf("Could not get status for OBCP %.5s\n", def->id);
   }
   return status;
}

/* -----------------------------------------------------------------------
 * Trigger state machine
 * ----------------------------------------------------------------------- */

typedef enum {
   PHASE_INIT,
   PHASE_IO_WRITE_TEST,
   PHASE_DATAPOOL_TEST,
   PHASE_CONCURRENCY_WAIT_TEST1,
   PHASE_CONCURRENCY_ALL_RUNNING,
} Harness_Phase;

void harness_PI_trigger(void)
{
   static Harness_Phase phase = PHASE_INIT;

   switch (phase) {

      /* -----------------------------------------------------------------
       * Start the engine and kick off the IO write test OBCP.
       * ----------------------------------------------------------------- */
      case PHASE_INIT: {
         harness_RI_start_obcp_engine();

         if (!load_obcp(&OBCP_IOTEST)) return;
         if (!activate_obcp(&OBCP_IOTEST)) return;

         printf("IO write test OBCP activated\n");
         io_write_test_active = true;
         io_test_msg_index = 0;
         phase = PHASE_IO_WRITE_TEST;
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the IO write test OBCP to complete, then kick off the
       * datapool test OBCP.
       * ----------------------------------------------------------------- */
      case PHASE_IO_WRITE_TEST: {
         const asn1SccOBCP_Execution_Status sio = get_status(&OBCP_IOTEST);

         if (sio == OBCP_Execution_Status_inactive) {
            io_write_test_active = false;
            if (io_test_msg_index != IO_TEST_EXPECTED_COUNT) {
               printf("IO test ERROR: expected %zu messages, received %zu\n",
                      IO_TEST_EXPECTED_COUNT, io_test_msg_index);
            } else {
               printf("IO write tests finished — all %zu messages verified OK\n",
                      IO_TEST_EXPECTED_COUNT);
            }

            if (!load_obcp(&OBCP_DPTEST)) return;
            if (!activate_obcp(&OBCP_DPTEST)) return;

            printf("Datapool test OBCP activated\n");
            phase = PHASE_DATAPOOL_TEST;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the datapool test OBCP to complete, then launch the
       * concurrency tests (TEST1 and TEST2 run in parallel).
       * ----------------------------------------------------------------- */
      case PHASE_DATAPOOL_TEST: {
         const asn1SccOBCP_Execution_Status sdp = get_status(&OBCP_DPTEST);

         if (sdp == OBCP_Execution_Status_inactive) {
            printf("Datapool tests finished\n");

            if (!load_obcp(&OBCP_TEST1)) return;
            if (!load_obcp(&OBCP_TEST2)) return;
            if (!load_obcp(&OBCP_TEST3)) return;

            /* TEST1 and TEST2 start immediately; TEST3 waits for TEST1 */
            if (!activate_obcp(&OBCP_TEST1)) return;
            if (!activate_obcp(&OBCP_TEST2)) return;

            printf("TEST1 (3 s) and TEST2 (5 s) activated\n");
            phase = PHASE_CONCURRENCY_WAIT_TEST1;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for TEST1 to complete, then activate TEST3 to exercise
       * concurrent execution of two active OBCPs.
       * ----------------------------------------------------------------- */
      case PHASE_CONCURRENCY_WAIT_TEST1: {
         const asn1SccOBCP_Execution_Status s1 = get_status(&OBCP_TEST1);

         printf("Status — TEST1: %d  TEST2: %d\n",
                s1, get_status(&OBCP_TEST2));

         if (s1 == OBCP_Execution_Status_inactive) {
            printf("TEST1 finished — activating TEST3 (3 s)\n");
            if (!activate_obcp(&OBCP_TEST3)) return;
            phase = PHASE_CONCURRENCY_ALL_RUNNING;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for both remaining OBCPs to finish and exit.
       * ----------------------------------------------------------------- */
      case PHASE_CONCURRENCY_ALL_RUNNING: {
         const asn1SccOBCP_Execution_Status s2 = get_status(&OBCP_TEST2);
         const asn1SccOBCP_Execution_Status s3 = get_status(&OBCP_TEST3);

         printf("Status — TEST2: %d  TEST3: %d\n", s2, s3);

         if (s2 == OBCP_Execution_Status_inactive &&
             s3 == OBCP_Execution_Status_inactive)
         {
            printf("All OBCPs finished — exiting\n");
            kill(getpid(), SIGTERM);
         }
         break;
      }
   }
}


