/* Body file for function harness
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "harness.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <signal.h>
#include <time.h>
#include <unistd.h>


void harness_startup(void)
{
   // NOP
}

void harness_PI_get_current_time
      (asn1SccT_Int32 *OUT_seconds,
       asn1SccT_Int32 *OUT_milliseconds)

{
   struct timespec ts;
   clock_gettime(CLOCK_MONOTONIC, &ts);
   *OUT_seconds      = (asn1SccT_Int32)ts.tv_sec;
   *OUT_milliseconds = (asn1SccT_Int32)(ts.tv_nsec / 1000000L);
}


/* -----------------------------------------------------------------------
 * In-memory parameter store (supports up to PARAM_STORE_SIZE parameters)
 * ----------------------------------------------------------------------- */

#define PARAM_STORE_SIZE 32

typedef struct {
   asn1SccOBCP_Parameter_Id    id;
   asn1SccOBCP_Parameter_Value value;
   bool                        valid;
} Harness_ParamEntry;

static Harness_ParamEntry param_store[PARAM_STORE_SIZE];

/* ----------------------------------------------------------------------- */

void harness_PI_get_parameter_value
      (const asn1SccOBCP_Parameter_Id *IN_id,
       const asn1SccOBCP_Parameter_Type *IN_parameter_type,
       asn1SccOBCP_Parameter_Value *OUT_parameter_value)

{
   for (int i = 0; i < PARAM_STORE_SIZE; i++) {
      if (param_store[i].valid && param_store[i].id == *IN_id) {
         *OUT_parameter_value = param_store[i].value;
         return;
      }
   }
   /* Parameter not found: return a default zero integer value */
   OUT_parameter_value->kind        = OBCP_Parameter_Value_int_value_PRESENT;
   OUT_parameter_value->u.int_value = 0;
}


/* -----------------------------------------------------------------------
 * IO write test verification
 * ----------------------------------------------------------------------- */

static const char * const io_test_expected[] = {
   "IO test: single-line write\n",
   "IO test: numeric value: 42\n",
   "IO test: string concatenation\n",
};
#define IO_TEST_EXPECTED_COUNT \
   (sizeof(io_test_expected) / sizeof(io_test_expected[0]))

static size_t io_test_msg_index  = 0;
static bool   io_write_test_active = false;

/* ----------------------------------------------------------------------- */

void harness_PI_output_message
      (const asn1SccOBCP_Text *IN_text)

{
   printf("%s", *IN_text);

   if (io_write_test_active) {
      if (io_test_msg_index >= IO_TEST_EXPECTED_COUNT) {
         printf("IO test ERROR: unexpected extra message: \"%s\"\n", *IN_text);
      } else if (strcmp(*IN_text, io_test_expected[io_test_msg_index]) != 0) {
         printf("IO test ERROR: message %zu: expected \"%s\", got \"%s\"\n",
                io_test_msg_index,
                io_test_expected[io_test_msg_index],
                *IN_text);
      }
      io_test_msg_index++;
   }
}


/* -----------------------------------------------------------------------
 * Events test verification
 * ----------------------------------------------------------------------- */

static const asn1SccOBCP_Event_Id events_test_expected[] = { 101, 202, 303 };
#define EVENTS_TEST_EXPECTED_COUNT \
   (sizeof(events_test_expected) / sizeof(events_test_expected[0]))

static size_t events_test_received_count = 0;
static bool   events_test_all_ok         = true;
static bool   events_test_active         = false;

/* ----------------------------------------------------------------------- */

void harness_PI_send_event( const asn1SccOBCP_Event_Id * event_id)
{
   printf("Event received: ID=%u\n", (unsigned)*event_id);

   if (events_test_active) {
      if (events_test_received_count >= EVENTS_TEST_EXPECTED_COUNT) {
         printf("Events test ERROR: unexpected extra event: ID=%u\n",
                (unsigned)*event_id);
         events_test_all_ok = false;
      } else if (*event_id != events_test_expected[events_test_received_count]) {
         printf("Events test ERROR: event %zu: expected ID=%u, got ID=%u\n",
                events_test_received_count,
                (unsigned)events_test_expected[events_test_received_count],
                (unsigned)*event_id);
         events_test_all_ok = false;
      }
      events_test_received_count++;
   }
}


/* -----------------------------------------------------------------------
 * Packets test channel and parameter IDs
 * ----------------------------------------------------------------------- */

/* Channel assignment for the packets test */
#define PKTTEST_ENV_INPUT_CHANNEL    0u  /* env injects onto this channel for OBCP_PKTRECV */
#define PKTTEST_INTER_OBCP_CHANNEL   1u  /* OBCP_PKTRECV sends here; harness relays back in */
#define PKTTEST_ENV_OUTPUT_CHANNEL   2u  /* OBCP_PKTSEND sends here; harness captures it */

/* Datapool parameter IDs written by the OBCPs */
#define PKTTEST_ENV_RECEIVE_PARAM_ID   20u /* 1 = env-input received correctly */
#define PKTTEST_INTER_OBCP_PARAM_ID    21u /* 1 = inter-OBCP exchange succeeded */
#define PKTTEST_NONBLOCKING_PARAM_ID   22u /* 1 = non-blocking / availability checks passed */
#define PKTTEST_CANSEND_PARAM_ID       23u /* 1 = cansendpacket checks passed */

/* Datapool parameter IDs used by the begin/end-step test */
#define STEPTEST_UNBLOCK_PARAM_ID      30u /* harness sets to 1 to unblock step 4 */
#define STEPTEST_REACHED_STEP_PARAM_ID 31u /* OBCP writes the ID of each step it begins */
#define STEPTEST_DONE_PARAM_ID         32u /* OBCP sets to 1 when all steps have completed */

/* Expected last step number and total step count */
#define STEPTEST_BLOCKING_STEP         4
#define STEPTEST_LAST_STEP             6

/* Datapool parameter IDs used by the abort/stop tests */
#define STOPTEST_UNBLOCK_PARAM_ID      50u /* harness sets to 1 to unblock step 2 */
#define STOPTEST_STEP1_PARAM_ID        40u /* OBCP writes 1 in step 1 body */
#define STOPTEST_STEP2_PARAM_ID        41u /* OBCP writes 1 in step 2 body */
#define STOPTEST_STEP3_PARAM_ID        42u /* OBCP writes 1 in step 3 body (stop fires at endstep) */
#define STOPTEST_STEP4_PARAM_ID        43u /* must remain 0 — not reached after stop */
#define STOPTEST_STEP5_PARAM_ID        44u /* must remain 0 — not reached after stop */
#define STOPTEST_DONE_PARAM_ID         45u /* must remain 0 — not reached after stop */
#define STOPTEST_BLOCKING_STEP         2   /* step that blocks until harness unblocks */
#define STOPTEST_TARGET_STEP           3   /* stop is requested at this step */

/* Expected content of the 16-byte packet sent from OBCP_PKTSEND to env */
static const unsigned char pkttest_expected_env_output[16] = {
   0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7,
   0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF
};

static bool              pkttest_active              = false;
static bool              pkttest_env_output_received = false;
static asn1SccOBCP_Packet pkttest_env_output_packet;

/* ----------------------------------------------------------------------- */

void harness_PI_send_packet
      (const asn1SccOBCP_Channel_Id *IN_channel,
       const asn1SccOBCP_Packet *IN_packet,
       asn1SccT_Boolean *OUT_success)

{
   *OUT_success = TRUE;

   if (*IN_channel == PKTTEST_INTER_OBCP_CHANNEL) {
      /* Relay the inter-OBCP packet back into the engine on the same channel
       * so that the receiving OBCP can pick it up via receivepacket(). */
      printf("Packets test: relaying %d-byte packet on channel %u\n",
             IN_packet->nCount, (unsigned)*IN_channel);
      asn1SccT_Boolean receive_success = FALSE;
      while (!receive_success)
      {
         // Push the packet untill success
         harness_RI_receive_packet(IN_channel, IN_packet, &receive_success);
      }
      return;
   }

   if (*IN_channel == PKTTEST_ENV_OUTPUT_CHANNEL && pkttest_active) {
      /* Capture the packet sent from the OBCP to the environment. */
      printf("Packets test: received %d-byte packet from OBCP on channel %u\n",
             IN_packet->nCount, (unsigned)*IN_channel);
      pkttest_env_output_received = true;
      pkttest_env_output_packet   = *IN_packet;
      return;
   }

   printf("Packet received on channel %u (%d bytes)\n",
          (unsigned)*IN_channel, IN_packet->nCount);
}


void harness_PI_set_parameter_value
      (const asn1SccOBCP_Parameter_Id *IN_id,
       const asn1SccOBCP_Parameter_Value *IN_parameter_value)

{
   int empty = -1;
   for (int i = 0; i < PARAM_STORE_SIZE; i++) {
      if (param_store[i].valid && param_store[i].id == *IN_id) {
         param_store[i].value = *IN_parameter_value;
         return;
      }
      if (!param_store[i].valid && empty < 0) {
         empty = i;
      }
   }
   if (empty >= 0) {
      param_store[empty].id    = *IN_id;
      param_store[empty].value = *IN_parameter_value;
      param_store[empty].valid = true;
   }
}


/* -----------------------------------------------------------------------
 * Harness OBCP definitions
 * ----------------------------------------------------------------------- */

typedef struct {
   asn1SccOBCP_Id   id;
   const char      *src;
} Harness_ObcpDef;

/* IO write test OBCP: exercises the obcpio.write function by sending
 * plain text, numeric conversions and string concatenation to the output.
 */
static const Harness_ObcpDef OBCP_IOTEST = {
   .id  = {'I','O','T','S','T'},
   .src =
      "import obcpio\n"
      "obcpio.write('IO test: single-line write\\n')\n"
      "obcpio.write('IO test: numeric value: ' + str(42) + '\\n')\n"
      "obcpio.write('IO test: ' + 'string ' + 'concatenation\\n')\n"
};

/* Datapool test OBCP: exercises write and read of int, enum, float and bool
 * parameters using the MicroPython obcpdatapool module.  Parameter IDs:
 *   1 = integer   2 = enum   3 = float   4 = bool
 */
static const Harness_ObcpDef OBCP_DPTEST = {
   .id  = {'D','P','T','S','T'},
   .src =
      "import obcpdatapool\n"
      "import obcpio\n"
      "obcpdatapool.writeintparameter(1, -42)\n"
      "v = obcpdatapool.readintparameter(1)\n"
      "if v != -42: raise RuntimeError('int fail')\n"
      "obcpio.write('DP int OK: ' + str(v) + '\\n')\n"
      "obcpdatapool.writeenumparameter(2, 7)\n"
      "v = obcpdatapool.readenumparameter(2)\n"
      "if v != 7: raise RuntimeError('enum fail')\n"
      "obcpio.write('DP enum OK: ' + str(v) + '\\n')\n"
      "obcpdatapool.writefloatparameter(3, 2.718)\n"
      "v = obcpdatapool.readfloatparameter(3)\n"
      "obcpio.write('DP float OK: ' + str(v) + '\\n')\n"
      "obcpdatapool.writeboolparameter(4, True)\n"
      "v = obcpdatapool.readboolparameter(4)\n"
      "if not v: raise RuntimeError('bool fail')\n"
      "obcpio.write('DP bool OK: ' + str(v) + '\\n')\n"
};

/* Events test OBCP: sends a known sequence of events via obcpevents.sendevent.
 * The harness verifies that all three events arrive in the expected order.
 * Event IDs: 101, 202, 303
 */
static const Harness_ObcpDef OBCP_EVTEST = {
   .id  = {'E','V','T','S','T'},
   .src =
      "import obcpevents\n"
      "obcpevents.sendevent(101)\n"
      "obcpevents.sendevent(202)\n"
      "obcpevents.sendevent(303)\n"
};

static const Harness_ObcpDef OBCP_TEST1 = {
   .id  = {'T','E','S','T','1'},
   .src = "import obcptime\nobcptime.wait(3000)\n"
};

static const Harness_ObcpDef OBCP_TEST2 = {
   .id  = {'T','E','S','T','2'},
   .src = "import obcptime\nobcptime.wait(5000)\n"
};

static const Harness_ObcpDef OBCP_TEST3 = {
   .id  = {'T','E','S','T','3'},
   .src = "import obcptime\nobcptime.wait(3000)\n"
};

/* Gettime test OBCP: records the time before and after a known wait period,
 * stores the elapsed milliseconds and a pass/fail flag in the datapool.
 * Parameter IDs: 10 = elapsed milliseconds (int), 11 = passed (int: 1=pass)
 * Tolerance window: ±200 ms around the nominal 2000 ms wait.
 */
#define TIMETEST_WAIT_MS       2000
#define TIMETEST_TOLERANCE_MS   200
#define TIMETEST_ELAPSED_PARAM_ID  10
#define TIMETEST_PASSED_PARAM_ID   11

static const Harness_ObcpDef OBCP_TIMETEST = {
   .id  = {'T','I','M','E','T'},
   .src =
      "import obcptime\n"
      "import obcpdatapool\n"
      "import obcpio\n"
      "t0 = obcptime.gettime()\n"
      "obcptime.wait(2000)\n"
      "t1 = obcptime.gettime()\n"
      "elapsed = (t1[0] - t0[0]) * 1000 + (t1[1] - t0[1])\n"
      "obcpdatapool.writeintparameter(10, elapsed)\n"
      "passed = 1 if 1800 <= elapsed <= 2200 else 0\n"
      "obcpdatapool.writeintparameter(11, passed)\n"
      "obcpio.write('Gettime test: elapsed=' + str(elapsed) + 'ms, passed=' + str(passed) + '\\n')\n"
};

/* Packet receive test OBCP: runs concurrently with OBCP_PKTSEND.
 * Tests:
 *  - ispacketavailable / getchannelwithpacketavailable / non-blocking receivepacket
 *  - Timed receive (500 ms) of a 4-byte env-injected packet on channel 0
 *  - Sending an 8-byte reply to OBCP_PKTSEND on channel 1
 * Results are stored in the datapool (params 20 and 22).
 */
static const Harness_ObcpDef OBCP_PKTRECV = {
   .id  = {'P','K','T','R','V'},
   .src =
      "import obcppackets\n"
      "import obcpdatapool\n"
      "no_avail = 0 if obcppackets.ispacketavailable(3) else 1\n"
      "first_chan = obcppackets.getchannelwithpacketavailable()\n"
      "first_avail_ok = 1 if first_chan == 0 else 0\n"
      "none_pkt = obcppackets.receivepacket(3, 0)\n"
      "none_ok = 1 if none_pkt is None else 0\n"
      "obcpdatapool.writeintparameter(22, 1 if (no_avail and first_avail_ok and none_ok) else 0)\n"
      "pkt = obcppackets.receivepacket(0, 500)\n"
      "if pkt is not None and len(pkt) == 4 and pkt[0] == 0xAA and pkt[3] == 0xDD:\n"
      "    obcpdatapool.writeintparameter(20, 1)\n"
      "else:\n"
      "    obcpdatapool.writeintparameter(20, 0)\n"
      "obcppackets.sendpacket(1, bytes([0x11,0x22,0x33,0x44,0x55,0x66,0x77,0x88]))\n"
};

/* Packet send test OBCP: runs concurrently with OBCP_PKTRECV.
 * Tests:
 *  - cansendpacket with a valid channel (2) and an out-of-range channel (99)
 *  - Blocking receive (UINT32_MAX timeout) of the 8-byte packet from OBCP_PKTRECV
 *  - Sending a 16-byte packet to the environment on channel 2
 * Results are stored in the datapool (params 21 and 23).
 */
static const Harness_ObcpDef OBCP_PKTSEND = {
   .id  = {'P','K','T','S','D'},
   .src =
      "import obcppackets\n"
      "import obcpdatapool\n"
      "can_valid = 1 if obcppackets.cansendpacket(2) else 0\n"
      "can_invalid = 0 if obcppackets.cansendpacket(99) else 1\n"
      "obcpdatapool.writeintparameter(23, 1 if (can_valid and can_invalid) else 0)\n"
      "pkt = obcppackets.receivepacket(1, 4294967295)\n"
      "if pkt is not None and len(pkt) == 8 and pkt[0] == 0x11 and pkt[7] == 0x88:\n"
      "    obcpdatapool.writeintparameter(21, 1)\n"
      "else:\n"
      "    obcpdatapool.writeintparameter(21, 0)\n"
      "obcppackets.sendpacket(2, bytes([0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,"
                                       "0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF]))\n"
};

/* Step test OBCP: executes six numbered steps using obcpcontrol.beginstep /
 * endstep.  Steps 1-3 complete immediately; step 4 blocks inside beginstep
 * until the harness sets STEPTEST_UNBLOCK_PARAM_ID (30) to 1 in the
 * datapool; steps 5-6 complete immediately.  The OBCP records each begun
 * step number in STEPTEST_REACHED_STEP_PARAM_ID (31) and writes 1 to
 * STEPTEST_DONE_PARAM_ID (32) when all steps have finished.
 */
static const Harness_ObcpDef OBCP_STEPTEST = {
   .id  = {'S','T','P','T','S'},
   .src =
      "import obcpcontrol\n"
      "import obcpdatapool\n"
      "import obcptime\n"
      "obcpcontrol.beginstep(1)\n"
      "obcpdatapool.writeintparameter(31, 1)\n"
      "obcpcontrol.endstep(1, True)\n"
      "obcpcontrol.beginstep(2)\n"
      "obcpdatapool.writeintparameter(31, 2)\n"
      "obcpcontrol.endstep(2, True)\n"
      "obcpcontrol.beginstep(3)\n"
      "obcpdatapool.writeintparameter(31, 3)\n"
      "obcpcontrol.endstep(3, True)\n"
      "obcpcontrol.beginstep(4)\n"
      "obcpdatapool.writeintparameter(31, 4)\n"
      "while obcpdatapool.readintparameter(30) == 0:\n"
      "    obcptime.wait(10)\n"
      "obcpcontrol.endstep(4, True)\n"
      "obcpcontrol.beginstep(5)\n"
      "obcpdatapool.writeintparameter(31, 5)\n"
      "obcpcontrol.endstep(5, True)\n"
      "obcpcontrol.beginstep(6)\n"
      "obcpdatapool.writeintparameter(31, 6)\n"
      "obcpcontrol.endstep(6, True)\n"
      "obcpdatapool.writeintparameter(32, 1)\n"
};

/* Abort test OBCP: runs an infinite loop and never terminates on its own.
 * The harness polls until active_and_running, calls abort_obcp, then verifies
 * that the OBCP transitions back to inactive.
 */
static const Harness_ObcpDef OBCP_ABORTTEST = {
   .id  = {'A','B','R','T','T'},
   .src =
      "import obcptime\n"
      "while True:\n"
      "    obcptime.wait(10)\n"
};

/* Stop test OBCP: five steps with datapool writes; step 2 blocks until the
 * harness sets STOPTEST_UNBLOCK_PARAM_ID (50) to 1.  The harness requests a
 * stop at step 3 while the OBCP is blocked in step 2.  After unblocking, the
 * OBCP finishes step 2, executes the body of step 3 (writing param 42), then
 * endstep(3) triggers the stop.  Steps 4-5 and the done flag must not run.
 */
static const Harness_ObcpDef OBCP_STOPTEST = {
   .id  = {'S','T','O','P','T'},
   .src =
      "import obcpcontrol\n"
      "import obcpdatapool\n"
      "import obcptime\n"
      "obcpcontrol.beginstep(1)\n"
      "obcpdatapool.writeintparameter(40, 1)\n"
      "obcpcontrol.endstep(1, True)\n"
      "obcpcontrol.beginstep(2)\n"
      "obcpdatapool.writeintparameter(41, 1)\n"
      "while obcpdatapool.readintparameter(50) == 0:\n"
      "    obcptime.wait(10)\n"
      "obcpcontrol.endstep(2, True)\n"
      "obcpcontrol.beginstep(3)\n"
      "obcpdatapool.writeintparameter(42, 1)\n"
      "obcpcontrol.endstep(3, True)\n"
      "obcpcontrol.beginstep(4)\n"
      "obcpdatapool.writeintparameter(43, 1)\n"
      "obcpcontrol.endstep(4, True)\n"
      "obcpcontrol.beginstep(5)\n"
      "obcpdatapool.writeintparameter(44, 1)\n"
      "obcpcontrol.endstep(5, True)\n"
      "obcpdatapool.writeintparameter(45, 1)\n"
};

/* -----------------------------------------------------------------------
 * Helpers
 * ----------------------------------------------------------------------- */

static bool load_obcp(const Harness_ObcpDef *def)
{
   asn1SccOBCP_Code code;
   const size_t len = strlen(def->src) + 1;
   memcpy(code.arr, def->src, len);
   code.nCount = (int)len;

   asn1SccT_Boolean ok = FALSE;
   harness_RI_load_obcp(&def->id, &code, &ok);
   if (!ok) {
      printf("Could not load OBCP %.5s\n", def->id);
   }
   return (bool)ok;
}

static bool activate_obcp(const Harness_ObcpDef *def)
{
   asn1SccT_Boolean ok = FALSE;
   harness_RI_activate_obcp(&def->id, &ok);
   if (!ok) {
      printf("Could not activate OBCP %.5s\n", def->id);
   }
   return (bool)ok;
}

static asn1SccOBCP_Execution_Status get_status(const Harness_ObcpDef *def)
{
   asn1SccOBCP_Execution_Status status = OBCP_Execution_Status_inactive;
   asn1SccOBCP_Step_Id step_id = 0;
   asn1SccT_Boolean ok = FALSE;
   harness_RI_get_obcp_status(&def->id, &status, &step_id, &ok);
   if (!ok) {
      printf("Could not get status for OBCP %.5s\n", def->id);
   }
   return status;
}

static asn1SccOBCP_Step_Id get_current_step(const Harness_ObcpDef *def)
{
   asn1SccOBCP_Execution_Status status = OBCP_Execution_Status_inactive;
   asn1SccOBCP_Step_Id step_id = 0;
   asn1SccT_Boolean ok = FALSE;
   harness_RI_get_obcp_status(&def->id, &status, &step_id, &ok);
   if (!ok) {
      printf("Could not get status for OBCP %.5s\n", def->id);
   }
   return step_id;
}

static void unload_obcp(const Harness_ObcpDef *def)
{
   asn1SccT_Boolean ok = FALSE;
   harness_RI_unload_obcp(&def->id, &ok);
   if (!ok) {
      printf("Could not unload OBCP %.5s\n", def->id);
   }
}

static bool abort_obcp(const Harness_ObcpDef *def)
{
   asn1SccT_Boolean ok = FALSE;
   harness_RI_abort_obcp(&def->id, &ok);
   if (!ok) {
      printf("Could not abort OBCP %.5s\n", def->id);
   }
   return (bool)ok;
}

static bool stop_obcp_at(const Harness_ObcpDef *def,
                          asn1SccOBCP_Step_Id step_id)
{
   asn1SccT_Boolean ok = FALSE;
   harness_RI_stop_obcp(&def->id, &step_id, &ok);
   if (!ok) {
      printf("Could not stop OBCP %.5s at step %u\n",
             def->id, (unsigned)step_id);
   }
   return (bool)ok;
}

/* -----------------------------------------------------------------------
 * Test result table
 * ----------------------------------------------------------------------- */

typedef enum {
   TEST_NOT_RUN = 0,
   TEST_PASS,
   TEST_FAIL
} Harness_TestStatus;

typedef struct {
   const char        *name;
   Harness_TestStatus status;
} Harness_TestResult;

typedef enum {
   T_IO_WRITE        = 0,
   T_DATAPOOL,
   T_EVENTS,
   T_STEP_CONTROL,
   T_CONCURRENCY,
   T_GETTIME,
   T_PKT_ENV_RECV,
   T_PKT_INTER_OBCP,
   T_PKT_NONBLOCKING,
   T_PKT_CANSEND,
   T_PKT_ENV_SEND,
   T_ABORT,
   T_STOP,
   T_COUNT
} Harness_TestIndex;

static Harness_TestResult test_results[T_COUNT] = {
   [T_IO_WRITE]        = { "IO write output",                          TEST_NOT_RUN },
   [T_DATAPOOL]        = { "Datapool read/write (int/enum/float/bool)", TEST_NOT_RUN },
   [T_EVENTS]          = { "Events sequence",                          TEST_NOT_RUN },
   [T_STEP_CONTROL]    = { "Step control (beginstep/endstep)",         TEST_NOT_RUN },
   [T_CONCURRENCY]     = { "Concurrent OBCP execution",                TEST_NOT_RUN },
   [T_GETTIME]         = { "Gettime accuracy",                         TEST_NOT_RUN },
   [T_PKT_ENV_RECV]    = { "Packet: Env->OBCP receive (timed)",        TEST_NOT_RUN },
   [T_PKT_INTER_OBCP]  = { "Packet: OBCP-to-OBCP exchange",           TEST_NOT_RUN },
   [T_PKT_NONBLOCKING] = { "Packet: non-blocking + availability",      TEST_NOT_RUN },
   [T_PKT_CANSEND]     = { "Packet: cansendpacket",                    TEST_NOT_RUN },
   [T_PKT_ENV_SEND]    = { "Packet: OBCP->Env send",                   TEST_NOT_RUN },
   [T_ABORT]           = { "Abort OBCP (terminates infinite loop)",    TEST_NOT_RUN },
   [T_STOP]            = { "Stop OBCP at endstep boundary",            TEST_NOT_RUN },
};

static void test_record(Harness_TestIndex idx, bool passed)
{
   test_results[idx].status = passed ? TEST_PASS : TEST_FAIL;
}

static void report_final_results(void)
{
   static const char * const status_str[] = { "NOT RUN", "PASS   ", "FAIL   " };
   bool all_pass = true;
   printf("\n========================================\n");
   printf(" Test Results\n");
   printf("========================================\n");
   for (int i = 0; i < T_COUNT; i++) {
      const Harness_TestStatus s = test_results[i].status;
      if (s != TEST_PASS) { all_pass = false; }
      printf("  [%s] %s\n", status_str[s], test_results[i].name);
   }
   printf("----------------------------------------\n");
   printf("  Overall: %s\n", all_pass ? "PASS" : "FAIL");
   printf("========================================\n");
}

/* -----------------------------------------------------------------------
 * Trigger state machine
 * ----------------------------------------------------------------------- */

typedef enum {
   PHASE_INIT,
   PHASE_IO_WRITE_TEST,
   PHASE_DATAPOOL_TEST,
   PHASE_EVENTS_TEST,
   PHASE_STEP_TEST_WAIT_STEP4,
   PHASE_STEP_TEST_COMPLETE,
   PHASE_CONCURRENCY_WAIT_TEST1,
   PHASE_CONCURRENCY_ALL_RUNNING,
   PHASE_GETTIME_TEST,
   PHASE_PACKETS_INIT,
   PHASE_PACKETS_RUNNING,
   PHASE_ABORT_TEST_RUNNING,
   PHASE_ABORT_TEST_WAIT,
   PHASE_STOP_TEST_RUNNING,
   PHASE_STOP_TEST_WAIT,
} Harness_Phase;

void harness_PI_trigger(void)
{
   static Harness_Phase phase = PHASE_INIT;

   switch (phase) {

      /* -----------------------------------------------------------------
       * Start the engine and kick off the IO write test OBCP.
       * ----------------------------------------------------------------- */
      case PHASE_INIT: {
         harness_RI_start_obcp_engine();

         if (!load_obcp(&OBCP_IOTEST)) return;
         if (!activate_obcp(&OBCP_IOTEST)) return;

         printf("IO write test OBCP activated\n");
         io_write_test_active = true;
         io_test_msg_index = 0;
         phase = PHASE_IO_WRITE_TEST;
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the IO write test OBCP to complete, then kick off the
       * datapool test OBCP.
       * ----------------------------------------------------------------- */
      case PHASE_IO_WRITE_TEST: {
         const asn1SccOBCP_Execution_Status sio = get_status(&OBCP_IOTEST);

         if (sio == OBCP_Execution_Status_inactive) {
            io_write_test_active = false;
            test_record(T_IO_WRITE, io_test_msg_index == IO_TEST_EXPECTED_COUNT);
            if (io_test_msg_index != IO_TEST_EXPECTED_COUNT) {
               printf("IO test ERROR: expected %zu messages, received %zu\n",
                      IO_TEST_EXPECTED_COUNT, io_test_msg_index);
            } else {
               printf("IO write tests finished — all %zu messages verified OK\n",
                      IO_TEST_EXPECTED_COUNT);
            }            unload_obcp(&OBCP_IOTEST);
            if (!load_obcp(&OBCP_DPTEST)) return;
            if (!activate_obcp(&OBCP_DPTEST)) return;

            printf("Datapool test OBCP activated\n");
            phase = PHASE_DATAPOOL_TEST;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the datapool test OBCP to complete, then launch the
       * concurrency tests (TEST1 and TEST2 run in parallel).
       * ----------------------------------------------------------------- */
      case PHASE_DATAPOOL_TEST: {
         const asn1SccOBCP_Execution_Status sdp = get_status(&OBCP_DPTEST);

         if (sdp == OBCP_Execution_Status_inactive) {
            test_record(T_DATAPOOL, true);
            printf("Datapool tests finished\n");
            unload_obcp(&OBCP_DPTEST);

            if (!load_obcp(&OBCP_EVTEST)) return;
            if (!activate_obcp(&OBCP_EVTEST)) return;

            printf("Events test OBCP activated\n");
            events_test_active         = true;
            events_test_received_count = 0;
            events_test_all_ok         = true;
            phase = PHASE_EVENTS_TEST;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the events test OBCP to complete, then verify that all
       * expected events were received, and launch the concurrency tests.
       * ----------------------------------------------------------------- */
      case PHASE_EVENTS_TEST: {
         const asn1SccOBCP_Execution_Status sev = get_status(&OBCP_EVTEST);

         if (sev == OBCP_Execution_Status_inactive) {
            events_test_active = false;

            const bool events_ok = events_test_all_ok &&
                                   events_test_received_count == EVENTS_TEST_EXPECTED_COUNT;
            test_record(T_EVENTS, events_ok);
            if (!events_ok) {
               printf("Events test FAILED: expected %zu events, received %zu%s\n",
                      EVENTS_TEST_EXPECTED_COUNT,
                      events_test_received_count,
                      events_test_all_ok ? "" : " (order/ID mismatch)");
            } else {
               printf("Events test PASSED: all %zu events received in correct order\n",
                      EVENTS_TEST_EXPECTED_COUNT);
            }
            unload_obcp(&OBCP_EVTEST);

            /* Initialise step test datapool entries to zero before loading */
            {
               const asn1SccOBCP_Parameter_Id unblock_id = STEPTEST_UNBLOCK_PARAM_ID;
               const asn1SccOBCP_Parameter_Id reached_id = STEPTEST_REACHED_STEP_PARAM_ID;
               const asn1SccOBCP_Parameter_Id done_id    = STEPTEST_DONE_PARAM_ID;
               asn1SccOBCP_Parameter_Value zero_val;
               zero_val.kind        = OBCP_Parameter_Value_int_value_PRESENT;
               zero_val.u.int_value = 0;
               harness_PI_set_parameter_value(&unblock_id, &zero_val);
               harness_PI_set_parameter_value(&reached_id, &zero_val);
               harness_PI_set_parameter_value(&done_id,    &zero_val);
            }

            if (!load_obcp(&OBCP_STEPTEST)) return;
            if (!activate_obcp(&OBCP_STEPTEST)) return;

            printf("Step test OBCP activated\n");
            phase = PHASE_STEP_TEST_WAIT_STEP4;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Poll until the OBCP reports that step 4 has begun, confirm it,
       * then unblock the OBCP by setting the unblock datapool parameter.
       * ----------------------------------------------------------------- */
      case PHASE_STEP_TEST_WAIT_STEP4: {
         const asn1SccOBCP_Step_Id current_step = get_current_step(&OBCP_STEPTEST);

         if (current_step == STEPTEST_BLOCKING_STEP) {
            printf("Step test: get_obcp_status reports step %u active — unblocking OBCP\n",
                   (unsigned)current_step);
            const asn1SccOBCP_Parameter_Id unblock_id = STEPTEST_UNBLOCK_PARAM_ID;
            asn1SccOBCP_Parameter_Value one_val;
            one_val.kind        = OBCP_Parameter_Value_int_value_PRESENT;
            one_val.u.int_value = 1;
            harness_PI_set_parameter_value(&unblock_id, &one_val);
            phase = PHASE_STEP_TEST_COMPLETE;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the step test OBCP to finish, then verify that all
       * steps were executed and launch the concurrency tests.
       * ----------------------------------------------------------------- */
      case PHASE_STEP_TEST_COMPLETE: {
         const asn1SccOBCP_Execution_Status ss = get_status(&OBCP_STEPTEST);

         if (ss == OBCP_Execution_Status_inactive) {
            const asn1SccOBCP_Parameter_Type int_type  = OBCP_Parameter_Type_integer_type;
            asn1SccOBCP_Parameter_Value v;
            const asn1SccOBCP_Parameter_Id reached_id = STEPTEST_REACHED_STEP_PARAM_ID;
            const asn1SccOBCP_Parameter_Id done_id    = STEPTEST_DONE_PARAM_ID;

            harness_PI_get_parameter_value(&reached_id, &int_type, &v);
            const int32_t last_step = v.u.int_value;
            harness_PI_get_parameter_value(&done_id, &int_type, &v);
            const bool steps_done = (v.u.int_value == 1);

            const bool step_ok = steps_done && last_step == STEPTEST_LAST_STEP;
            test_record(T_STEP_CONTROL, step_ok);
            if (step_ok) {
               printf("Step test PASSED: all %d steps completed, "
                      "step %d hold-and-release verified\n",
                      STEPTEST_LAST_STEP, STEPTEST_BLOCKING_STEP);
            } else {
               printf("Step test FAILED: steps_done=%d, last_step=%d "
                      "(expected %d)\n",
                      (int)steps_done, (int)last_step, STEPTEST_LAST_STEP);
            }

            unload_obcp(&OBCP_STEPTEST);

            if (!load_obcp(&OBCP_TEST1)) return;
            if (!load_obcp(&OBCP_TEST2)) return;
            if (!load_obcp(&OBCP_TEST3)) return;

            /* TEST1 and TEST2 start immediately; TEST3 waits for TEST1 */
            if (!activate_obcp(&OBCP_TEST1)) return;
            if (!activate_obcp(&OBCP_TEST2)) return;

            printf("TEST1 (3 s) and TEST2 (5 s) activated\n");
            phase = PHASE_CONCURRENCY_WAIT_TEST1;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for TEST1 to complete, then activate TEST3 to exercise
       * concurrent execution of two active OBCPs.
       * ----------------------------------------------------------------- */
      case PHASE_CONCURRENCY_WAIT_TEST1: {
         const asn1SccOBCP_Execution_Status s1 = get_status(&OBCP_TEST1);

         printf("Status — TEST1: %d  TEST2: %d\n",
                s1, get_status(&OBCP_TEST2));

         if (s1 == OBCP_Execution_Status_inactive) {
            printf("TEST1 finished — activating TEST3 (3 s)\n");            unload_obcp(&OBCP_TEST1);            if (!activate_obcp(&OBCP_TEST3)) return;
            phase = PHASE_CONCURRENCY_ALL_RUNNING;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for both remaining OBCPs to finish, then kick off the
       * gettime accuracy test.
       * ----------------------------------------------------------------- */
      case PHASE_CONCURRENCY_ALL_RUNNING: {
         const asn1SccOBCP_Execution_Status s2 = get_status(&OBCP_TEST2);
         const asn1SccOBCP_Execution_Status s3 = get_status(&OBCP_TEST3);

         printf("Status — TEST2: %d  TEST3: %d\n", s2, s3);

         if (s2 == OBCP_Execution_Status_inactive &&
             s3 == OBCP_Execution_Status_inactive)
         {
            test_record(T_CONCURRENCY, true);
            printf("Concurrency tests finished\n");
            unload_obcp(&OBCP_TEST2);
            unload_obcp(&OBCP_TEST3);

            if (!load_obcp(&OBCP_TIMETEST)) return;
            if (!activate_obcp(&OBCP_TIMETEST)) return;

            printf("Gettime test OBCP activated (waiting %d ms)\n",
                   TIMETEST_WAIT_MS);
            phase = PHASE_GETTIME_TEST;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the gettime test OBCP to complete, then read the
       * elapsed time and pass/fail flag from the datapool and report.
       * ----------------------------------------------------------------- */
      case PHASE_GETTIME_TEST: {
         const asn1SccOBCP_Execution_Status st = get_status(&OBCP_TIMETEST);

         if (st == OBCP_Execution_Status_inactive) {
            /* Read results written by the OBCP into the datapool */
            const asn1SccOBCP_Parameter_Id elapsed_id = TIMETEST_ELAPSED_PARAM_ID;
            const asn1SccOBCP_Parameter_Id passed_id  = TIMETEST_PASSED_PARAM_ID;
            const asn1SccOBCP_Parameter_Type int_type  = OBCP_Parameter_Type_integer_type;
            asn1SccOBCP_Parameter_Value elapsed_val, passed_val;

            harness_PI_get_parameter_value(&elapsed_id, &int_type, &elapsed_val);
            harness_PI_get_parameter_value(&passed_id,  &int_type, &passed_val);

            const int32_t elapsed_ms = elapsed_val.u.int_value;
            const int32_t passed     = passed_val.u.int_value;

            test_record(T_GETTIME, passed != 0);
            if (passed) {
               printf("Gettime test PASSED: elapsed=%d ms "
                      "(nominal=%d ms, tolerance=\u00b1%d ms)\n",
                      elapsed_ms, TIMETEST_WAIT_MS, TIMETEST_TOLERANCE_MS);
            } else {
               printf("Gettime test FAILED: elapsed=%d ms "
                      "(expected %d\u00b1%d ms)\n",
                      elapsed_ms, TIMETEST_WAIT_MS, TIMETEST_TOLERANCE_MS);
            }

            printf("Gettime test finished\n");
            unload_obcp(&OBCP_TIMETEST);
            phase = PHASE_PACKETS_INIT;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Pre-inject the env-input packet on channel 0, then activate
       * OBCP_PKTRECV and OBCP_PKTSEND concurrently.
       * ----------------------------------------------------------------- */
      case PHASE_PACKETS_INIT: {
         /* Inject a 4-byte packet from the environment into channel 0.
          * OBCP_PKTRECV will pick it up with a timed receivepacket(). */
         const asn1SccOBCP_Channel_Id ch0 = PKTTEST_ENV_INPUT_CHANNEL;
         asn1SccOBCP_Packet env_in;
         memset(&env_in, 0, sizeof(env_in));
         env_in.arr[0] = (byte)0xAA;
         env_in.arr[1] = (byte)0xBB;
         env_in.arr[2] = (byte)0xCC;
         env_in.arr[3] = (byte)0xDD;
         env_in.nCount = 4;
         asn1SccT_Boolean receive_success = FALSE;
         while (!receive_success)
         {
            harness_RI_receive_packet(&ch0, &env_in, &receive_success);
         }
         printf("Packets test: injected 4-byte env-input packet on channel 0\n");

         if (!load_obcp(&OBCP_PKTRECV)) return;
         if (!load_obcp(&OBCP_PKTSEND)) return;
         if (!activate_obcp(&OBCP_PKTRECV)) return;
         if (!activate_obcp(&OBCP_PKTSEND)) return;

         pkttest_active              = true;
         pkttest_env_output_received = false;
         printf("Packets test OBCPs activated (PKTRECV + PKTSEND running concurrently)\n");
         phase = PHASE_PACKETS_RUNNING;
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for both packet OBCPs to complete, then read datapool results
       * and verify all aspects of the packets test.
       * ----------------------------------------------------------------- */
      case PHASE_PACKETS_RUNNING: {
         const asn1SccOBCP_Execution_Status sr = get_status(&OBCP_PKTRECV);
         const asn1SccOBCP_Execution_Status ss = get_status(&OBCP_PKTSEND);

         if (sr == OBCP_Execution_Status_inactive &&
             ss == OBCP_Execution_Status_inactive)
         {
            pkttest_active = false;

            /* Read all four in-OBCP test outcomes from the datapool */
            const asn1SccOBCP_Parameter_Type int_type = OBCP_Parameter_Type_integer_type;
            asn1SccOBCP_Parameter_Value v;
            const asn1SccOBCP_Parameter_Id env_recv_id  = PKTTEST_ENV_RECEIVE_PARAM_ID;
            const asn1SccOBCP_Parameter_Id inter_id     = PKTTEST_INTER_OBCP_PARAM_ID;
            const asn1SccOBCP_Parameter_Id nonblock_id  = PKTTEST_NONBLOCKING_PARAM_ID;
            const asn1SccOBCP_Parameter_Id cansend_id   = PKTTEST_CANSEND_PARAM_ID;

            harness_PI_get_parameter_value(&env_recv_id,  &int_type, &v);
            const bool env_recv_ok  = (v.u.int_value == 1);
            harness_PI_get_parameter_value(&inter_id,     &int_type, &v);
            const bool inter_ok     = (v.u.int_value == 1);
            harness_PI_get_parameter_value(&nonblock_id,  &int_type, &v);
            const bool nonblock_ok  = (v.u.int_value == 1);
            harness_PI_get_parameter_value(&cansend_id,   &int_type, &v);
            const bool cansend_ok   = (v.u.int_value == 1);

            /* Verify the 16-byte packet sent from OBCP_PKTSEND to environment */
            bool env_out_ok = pkttest_env_output_received &&
                              (pkttest_env_output_packet.nCount == 16);
            if (env_out_ok) {
               for (int i = 0; i < 16; i++) {
                  if ((unsigned char)pkttest_env_output_packet.arr[i] !=
                      pkttest_expected_env_output[i]) {
                     env_out_ok = false;
                     break;
                  }
               }
            }

            test_record(T_PKT_ENV_RECV,    env_recv_ok);
            test_record(T_PKT_INTER_OBCP,  inter_ok);
            test_record(T_PKT_NONBLOCKING, nonblock_ok);
            test_record(T_PKT_CANSEND,     cansend_ok);
            test_record(T_PKT_ENV_SEND,    env_out_ok);
            printf("Packets test results:\n");
            printf("  Env\u2192OBCP receive  (ch0, 4 B, 500 ms timeout): %s\n",
                   env_recv_ok ? "PASSED" : "FAILED");
            printf("  OBCP-to-OBCP exchange (ch0\u21921, 8 B, blocking):  %s\n",
                   inter_ok    ? "PASSED" : "FAILED");
            printf("  Non-blocking + availability checks (ch3):      %s\n",
                   nonblock_ok ? "PASSED" : "FAILED");
            printf("  cansendpacket (valid ch2 / invalid ch99):       %s\n",
                   cansend_ok  ? "PASSED" : "FAILED");
            printf("  OBCP\u2192Env send      (ch2, 16 B):                %s\n",
                   env_out_ok  ? "PASSED" : "FAILED");

            const bool all_ok = env_recv_ok && inter_ok && nonblock_ok &&
                                cansend_ok  && env_out_ok;
            printf("Packets test overall: %s\n", all_ok ? "PASSED" : "FAILED");
            unload_obcp(&OBCP_PKTRECV);
            unload_obcp(&OBCP_PKTSEND);

            if (!load_obcp(&OBCP_ABORTTEST)) return;
            if (!activate_obcp(&OBCP_ABORTTEST)) return;
            printf("Abort test OBCP activated (infinite loop)\n");
            phase = PHASE_ABORT_TEST_RUNNING;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Poll until the OBCP is actively running, then send abort.
       * ----------------------------------------------------------------- */
      case PHASE_ABORT_TEST_RUNNING: {
         const asn1SccOBCP_Execution_Status sa = get_status(&OBCP_ABORTTEST);
         if (sa == OBCP_Execution_Status_active_and_running) {
            printf("Abort test: OBCP is active_and_running \u2014 sending abort\n");
            abort_obcp(&OBCP_ABORTTEST);
            phase = PHASE_ABORT_TEST_WAIT;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the aborted OBCP to reach inactive, then launch the
       * stop test.
       * ----------------------------------------------------------------- */
      case PHASE_ABORT_TEST_WAIT: {
         const asn1SccOBCP_Execution_Status sa = get_status(&OBCP_ABORTTEST);
         if (sa == OBCP_Execution_Status_inactive) {
            test_record(T_ABORT, true);
            printf("Abort test PASSED: OBCP transitioned to inactive after abort\n");
            unload_obcp(&OBCP_ABORTTEST);

            /* Initialise stop test datapool entries to zero */
            {
               asn1SccOBCP_Parameter_Value zero_val;
               zero_val.kind        = OBCP_Parameter_Value_int_value_PRESENT;
               zero_val.u.int_value = 0;
               asn1SccOBCP_Parameter_Id pid;
               for (pid = STOPTEST_STEP1_PARAM_ID;
                    pid <= STOPTEST_DONE_PARAM_ID; ++pid) {
                  harness_PI_set_parameter_value(&pid, &zero_val);
               }
               const asn1SccOBCP_Parameter_Id unblock_id = STOPTEST_UNBLOCK_PARAM_ID;
               harness_PI_set_parameter_value(&unblock_id, &zero_val);
            }

            if (!load_obcp(&OBCP_STOPTEST)) return;
            if (!activate_obcp(&OBCP_STOPTEST)) return;
            printf("Stop test OBCP activated\n");
            phase = PHASE_STOP_TEST_RUNNING;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait until the OBCP is blocked in step 2; request stop at step 3
       * then unblock so it advances to step 3 and the stop fires there.
       * ----------------------------------------------------------------- */
      case PHASE_STOP_TEST_RUNNING: {
         const asn1SccOBCP_Step_Id current_step = get_current_step(&OBCP_STOPTEST);
         if (current_step == STOPTEST_BLOCKING_STEP) {
            printf("Stop test: OBCP is in step %u \u2014 requesting stop at step %u\n",
                   (unsigned)current_step, (unsigned)STOPTEST_TARGET_STEP);
            stop_obcp_at(&OBCP_STOPTEST, STOPTEST_TARGET_STEP);
            const asn1SccOBCP_Parameter_Id unblock_id = STOPTEST_UNBLOCK_PARAM_ID;
            asn1SccOBCP_Parameter_Value one_val;
            one_val.kind        = OBCP_Parameter_Value_int_value_PRESENT;
            one_val.u.int_value = 1;
            harness_PI_set_parameter_value(&unblock_id, &one_val);
            phase = PHASE_STOP_TEST_WAIT;
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the stopped OBCP to reach inactive, then verify that
       * steps 1-3 ran (params 40-42 == 1) and steps 4-5 did not
       * (params 43-45 == 0).
       * ----------------------------------------------------------------- */
      case PHASE_STOP_TEST_WAIT: {
         const asn1SccOBCP_Execution_Status ss = get_status(&OBCP_STOPTEST);
         if (ss == OBCP_Execution_Status_inactive) {
            const asn1SccOBCP_Parameter_Type int_type = OBCP_Parameter_Type_integer_type;
            asn1SccOBCP_Parameter_Value v;
            bool ok = true;
            asn1SccOBCP_Parameter_Id pid;

            /* Steps 1-3 body must have run (params 40-42 == 1) */
            for (pid = STOPTEST_STEP1_PARAM_ID;
                 pid <= STOPTEST_STEP3_PARAM_ID; ++pid) {
               harness_PI_get_parameter_value(&pid, &int_type, &v);
               if (v.u.int_value != 1) {
                  printf("Stop test FAILED: param %u expected 1, got %d "
                         "(step body before/at stop not executed)\n",
                         (unsigned)pid, (int)v.u.int_value);
                  ok = false;
               }
            }

            /* Steps 4-5 and done flag must NOT have run (params 43-45 == 0) */
            for (pid = STOPTEST_STEP4_PARAM_ID;
                 pid <= STOPTEST_DONE_PARAM_ID; ++pid) {
               harness_PI_get_parameter_value(&pid, &int_type, &v);
               if (v.u.int_value != 0) {
                  printf("Stop test FAILED: param %u expected 0, got %d "
                         "(execution continued past stop step)\n",
                         (unsigned)pid, (int)v.u.int_value);
                  ok = false;
               }
            }

            test_record(T_STOP, ok);
            if (ok) {
               printf("Stop test PASSED: OBCP stopped at endstep(%d); "
                      "steps 1-%d body executed, steps %d+ not reached\n",
                      STOPTEST_TARGET_STEP, STOPTEST_TARGET_STEP,
                      STOPTEST_TARGET_STEP + 1);
            }
            unload_obcp(&OBCP_STOPTEST);
            report_final_results();
            printf("All tests finished \u2014 exiting\n");
            kill(getpid(), SIGTERM);
         }
         break;
      }
   }
}


