/* Body file for function harness
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "harness.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#include <signal.h>
#include <time.h>
#include <unistd.h>

extern int32_t  Hal_SemaphoreCreate(void);
extern bool     Hal_SemaphoreObtain(int32_t id);
extern bool     Hal_SemaphoreRelease(int32_t id);
extern bool     Hal_SleepNs(uint64_t time_ns);
extern uint64_t Hal_GetElapsedTimeInNs(void);

static void report_final_results(void);
static void harness_report_failure_and_exit(const char *format, ...);

static int32_t harness_state_mutex = -1;

static asn1SccOBCP_Parameter_Value_selection harness_expected_parameter_kind(asn1SccOBCP_Parameter_Type parameter_type)
{
   switch (parameter_type) {
      case OBCP_Parameter_Type_integer_type:
         return OBCP_Parameter_Value_int_value_PRESENT;
      case OBCP_Parameter_Type_enumerated_type:
         return OBCP_Parameter_Value_enum_value_PRESENT;
      case OBCP_Parameter_Type_float_type:
         return OBCP_Parameter_Value_float_value_PRESENT;
      case OBCP_Parameter_Type_boolean_type:
         return OBCP_Parameter_Value_bool_value_PRESENT;
      default:
         harness_report_failure_and_exit("Parameter store ERROR: unsupported parameter type=%d\n",
                                         (int)parameter_type);
         return OBCP_Parameter_Value_NONE;
   }
}

static void harness_lock_state(void)
{
   if (harness_state_mutex >= 0) {
      (void)Hal_SemaphoreObtain(harness_state_mutex);
   }
}

static void harness_unlock_state(void)
{
   if (harness_state_mutex >= 0) {
      (void)Hal_SemaphoreRelease(harness_state_mutex);
   }
}

static void harness_error_printf(const char *format, ...)
{
   va_list args;

   va_start(args, format);
   vfprintf(stderr, format, args);
   va_end(args);
}

static void harness_report_failure_and_exit(const char *format, ...)
{
   va_list args;

   va_start(args, format);
   vfprintf(stderr, format, args);
   va_end(args);

   report_final_results();
   printf("All tests finished — exiting\n");
   kill(getpid(), SIGTERM);
}


void harness_startup(void)
{
   if (harness_state_mutex < 0) {
      harness_state_mutex = Hal_SemaphoreCreate();
   }
}

void harness_PI_get_current_time
      (asn1SccT_Int32 *OUT_seconds,
       asn1SccT_Int32 *OUT_milliseconds)

{
   const uint64_t elapsed_ns = Hal_GetElapsedTimeInNs();
   const uint64_t elapsed_ms = elapsed_ns / 1000000ULL;

   *OUT_seconds      = (asn1SccT_Int32)(elapsed_ms / 1000ULL);
   *OUT_milliseconds = (asn1SccT_Int32)(elapsed_ms % 1000ULL);
}


/* -----------------------------------------------------------------------
 * In-memory parameter store (supports up to PARAM_STORE_SIZE parameters)
 * ----------------------------------------------------------------------- */

#define PARAM_STORE_SIZE 32

typedef struct {
   asn1SccOBCP_Parameter_Id    id;
   asn1SccOBCP_Parameter_Value value;
   bool                        valid;
} Harness_ParamEntry;

static Harness_ParamEntry param_store[PARAM_STORE_SIZE];

/* ----------------------------------------------------------------------- */

void harness_PI_get_parameter_value
      (const asn1SccOBCP_Parameter_Id *IN_id,
       const asn1SccOBCP_Parameter_Type *IN_parameter_type,
       asn1SccOBCP_Parameter_Value *OUT_parameter_value)

{
   const asn1SccOBCP_Parameter_Value_selection expected_kind =
      harness_expected_parameter_kind(*IN_parameter_type);

   harness_lock_state();
   for (int i = 0; i < PARAM_STORE_SIZE; i++) {
      if (param_store[i].valid && param_store[i].id == *IN_id) {
         if (param_store[i].value.kind != expected_kind) {
            harness_unlock_state();
            harness_report_failure_and_exit("Parameter store ERROR: parameter ID=%u requested as type=%d but stored kind=%d\n",
                                            (unsigned)*IN_id,
                                            (int)*IN_parameter_type,
                                            (int)param_store[i].value.kind);
            return;
         }
         *OUT_parameter_value = param_store[i].value;
         harness_unlock_state();
         return;
      }
   }
   harness_unlock_state();
   harness_report_failure_and_exit("Parameter store ERROR: parameter ID=%u not found for requested type=%d\n",
                                   (unsigned)*IN_id,
                                   (int)*IN_parameter_type);
}


/* -----------------------------------------------------------------------
 * IO write test verification
 * ----------------------------------------------------------------------- */

static const char * const io_test_expected[] = {
   "IO test: single-line write\n",
   "IO test: numeric value: 42\n",
   "IO test: string concatenation\n",
};
#define OBCP_TEXT_COMPARE_LEN (sizeof(asn1SccOBCP_Text))
#define IO_TEST_EXPECTED_COUNT \
   (sizeof(io_test_expected) / sizeof(io_test_expected[0]))

static size_t io_test_msg_index  = 0;
static bool   io_write_test_active = false;
static bool   io_write_test_all_ok = true;

/* ----------------------------------------------------------------------- */

void harness_PI_output_message
      (const asn1SccOBCP_Text *IN_text)

{
   printf("%s", *IN_text);

   harness_lock_state();
   if (io_write_test_active) {
      if (io_test_msg_index >= IO_TEST_EXPECTED_COUNT) {
         io_write_test_all_ok = false;
         harness_error_printf("IO test ERROR: unexpected extra message: \"%s\"\n",
                              *IN_text);
      } else if (strncmp(*IN_text,
                         io_test_expected[io_test_msg_index],
                         OBCP_TEXT_COMPARE_LEN) != 0) {
         io_write_test_all_ok = false;
         harness_error_printf("IO test ERROR: message %zu: expected \"%s\", got \"%s\"\n",
                              io_test_msg_index,
                              io_test_expected[io_test_msg_index],
                              *IN_text);
      }
      io_test_msg_index++;
   }
   harness_unlock_state();
}


/* -----------------------------------------------------------------------
 * Events test verification
 * ----------------------------------------------------------------------- */

static const asn1SccOBCP_Event_Id events_test_expected[] = { 101, 202, 303 };
#define EVENTS_TEST_EXPECTED_COUNT \
   (sizeof(events_test_expected) / sizeof(events_test_expected[0]))

static size_t events_test_received_count = 0;
static bool   events_test_all_ok         = true;
static bool   events_test_active         = false;

/* ----------------------------------------------------------------------- */

void harness_PI_send_event( const asn1SccOBCP_Event_Id * event_id)
{
   printf("Event received: ID=%u\n", (unsigned)*event_id);

   harness_lock_state();
   if (events_test_active) {
      if (events_test_received_count >= EVENTS_TEST_EXPECTED_COUNT) {
         harness_error_printf("Events test ERROR: unexpected extra event: ID=%u\n",
                              (unsigned)*event_id);
         events_test_all_ok = false;
      } else if (*event_id != events_test_expected[events_test_received_count]) {
         harness_error_printf("Events test ERROR: event %zu: expected ID=%u, got ID=%u\n",
                              events_test_received_count,
                              (unsigned)events_test_expected[events_test_received_count],
                              (unsigned)*event_id);
         events_test_all_ok = false;
      }
      events_test_received_count++;
   }
   harness_unlock_state();
}


/* -----------------------------------------------------------------------
 * Packets test channel and parameter IDs
 * ----------------------------------------------------------------------- */

/* Channel assignment for the packets test */
#define PKTTEST_ENV_INPUT_CHANNEL    0u  /* env injects onto this channel for OBCP_PKTRECV */
#define PKTTEST_INTER_OBCP_CHANNEL   1u  /* OBCP_PKTRECV sends here; harness relays back in */
#define PKTTEST_ENV_OUTPUT_CHANNEL   2u  /* OBCP_PKTSEND sends here; harness captures it */

/* Datapool parameter IDs written by the OBCPs */
#define PKTTEST_ENV_RECEIVE_PARAM_ID   20u /* 1 = env-input received correctly */
#define PKTTEST_INTER_OBCP_PARAM_ID    21u /* 1 = inter-OBCP exchange succeeded */
#define PKTTEST_NONBLOCKING_PARAM_ID   22u /* 1 = non-blocking / availability checks passed */
#define PKTTEST_CANSEND_PARAM_ID       23u /* 1 = cansendpacket checks passed */

/* Datapool parameter IDs used by the begin/end-step test */
#define STEPTEST_UNBLOCK_PARAM_ID      30u /* harness sets to 1 to unblock step 4 */
#define STEPTEST_REACHED_STEP_PARAM_ID 31u /* OBCP writes the ID of each step it begins */
#define STEPTEST_DONE_PARAM_ID         32u /* OBCP sets to 1 when all steps have completed */

/* Expected last step number and total step count */
#define STEPTEST_BLOCKING_STEP         4
#define STEPTEST_LAST_STEP             6

/* Datapool parameter IDs used by the abort/stop tests */
#define STOPTEST_UNBLOCK_PARAM_ID      50u /* harness sets to 1 to unblock step 2 */
#define STOPTEST_STEP1_PARAM_ID        40u /* OBCP writes 1 in step 1 body */
#define STOPTEST_STEP2_PARAM_ID        41u /* OBCP writes 1 in step 2 body */
#define STOPTEST_STEP3_PARAM_ID        42u /* OBCP writes 1 in step 3 body (stop fires at endstep) */
#define STOPTEST_STEP4_PARAM_ID        43u /* must remain 0 — not reached after stop */
#define STOPTEST_STEP5_PARAM_ID        44u /* must remain 0 — not reached after stop */
#define STOPTEST_DONE_PARAM_ID         45u /* must remain 0 — not reached after stop */
#define STOPTEST_BLOCKING_STEP         2   /* step that blocks until harness unblocks */
#define STOPTEST_TARGET_STEP           3   /* stop is requested at this step */

/* Expected content of the 16-byte packet sent from OBCP_PKTSEND to env */
static const unsigned char pkttest_expected_env_output[16] = {
   0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7,
   0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF
};

static bool              pkttest_active              = false;
static bool              pkttest_env_output_received = false;
static asn1SccOBCP_Packet pkttest_env_output_packet;

#define HARNESS_PACKET_RETRY_SLEEP_NS   1000000ULL
#define HARNESS_PACKET_RETRY_TIMEOUT_NS 5000000000ULL

/* ----------------------------------------------------------------------- */

void harness_PI_send_packet
      (const asn1SccOBCP_Channel_Id *IN_channel,
       const asn1SccOBCP_Packet *IN_packet,
       asn1SccT_Boolean *OUT_success)

{
   bool capture_env_output = false;

   *OUT_success = TRUE;

   if (*IN_channel == PKTTEST_INTER_OBCP_CHANNEL) {
      /* Relay the inter-OBCP packet back into the engine on the same channel
       * so that the receiving OBCP can pick it up via receivepacket(). */
      printf("Packets test: relaying %d-byte packet on channel %u\n",
             IN_packet->nCount, (unsigned)*IN_channel);
      asn1SccT_Boolean receive_success = FALSE;
      const uint64_t deadline_ns = Hal_GetElapsedTimeInNs() + HARNESS_PACKET_RETRY_TIMEOUT_NS;
      while (!receive_success)
      {
         // Push the packet until success
         harness_RI_receive_packet(IN_channel, IN_packet, &receive_success);
         if (!receive_success) {
            if (Hal_GetElapsedTimeInNs() >= deadline_ns) {
               harness_error_printf("Packets test FAILED: timed out relaying packet on channel %u\n",
                                    (unsigned)*IN_channel);
               *OUT_success = FALSE;
               return;
            }
            (void)Hal_SleepNs(HARNESS_PACKET_RETRY_SLEEP_NS);
         }
      }
      return;
   }

   harness_lock_state();
   if (*IN_channel == PKTTEST_ENV_OUTPUT_CHANNEL && pkttest_active) {
      capture_env_output = true;
      pkttest_env_output_received = true;
      pkttest_env_output_packet   = *IN_packet;
   }
   harness_unlock_state();

   if (capture_env_output) {
      /* Capture the packet sent from the OBCP to the environment. */
      printf("Packets test: received %d-byte packet from OBCP on channel %u\n",
             IN_packet->nCount, (unsigned)*IN_channel);
      return;
   }

   printf("Packet received on channel %u (%d bytes)\n",
          (unsigned)*IN_channel, IN_packet->nCount);
}


void harness_PI_set_parameter_value
      (const asn1SccOBCP_Parameter_Id *IN_id,
       const asn1SccOBCP_Parameter_Value *IN_parameter_value)

{
   int empty = -1;

   harness_lock_state();
   for (int i = 0; i < PARAM_STORE_SIZE; i++) {
      if (param_store[i].valid && param_store[i].id == *IN_id) {
         param_store[i].value = *IN_parameter_value;
         harness_unlock_state();
         return;
      }
      if (!param_store[i].valid && empty < 0) {
         empty = i;
      }
   }
   if (empty >= 0) {
      param_store[empty].id    = *IN_id;
      param_store[empty].value = *IN_parameter_value;
      param_store[empty].valid = true;
   } else {
      harness_error_printf("Parameter store ERROR: no free slot for parameter ID=%u\n",
                           (unsigned)*IN_id);
   }
   harness_unlock_state();
}


/* -----------------------------------------------------------------------
 * Harness OBCP definitions
 * ----------------------------------------------------------------------- */

typedef struct {
   asn1SccOBCP_Id   id;
   const char      *src;
} Harness_ObcpDef;

typedef struct {
   asn1SccOBCP_Id      id;
   const unsigned char *code;
   size_t               len;
} Harness_PrecompiledObcpDef;

/* Precompiled OBCP. The source code is in example-obcp.py.
   The code contains obcpdatapool.writeintparameter(42, 1234).
*/

static const unsigned char OBCP_PRECOMPILED[] = {
  0x4d, 0x06, 0x00, 0x1f, 0x04, 0x00, 0x1e, 0x65, 0x78, 0x61, 0x6d, 0x70,
  0x6c, 0x65, 0x2d, 0x6f, 0x62, 0x63, 0x70, 0x2e, 0x70, 0x79, 0x00, 0x0f,
  0x18, 0x6f, 0x62, 0x63, 0x70, 0x64, 0x61, 0x74, 0x61, 0x70, 0x6f, 0x6f,
  0x6c, 0x00, 0x22, 0x77, 0x72, 0x69, 0x74, 0x65, 0x69, 0x6e, 0x74, 0x70,
  0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x00, 0x81, 0x38, 0x18,
  0x04, 0x01, 0x66, 0x80, 0x51, 0x1b, 0x02, 0x16, 0x02, 0x11, 0x02, 0x14,
  0x03, 0xaa, 0x22, 0x89, 0x52, 0x36, 0x02, 0x59, 0x51, 0x63
};

static const unsigned int OBCP_PRECOMPILED_LEN = 82;

static const Harness_PrecompiledObcpDef OBCP_PRECOMPILED_TEST = {
    .id = {'P','R','E','C','P'},
    .code = OBCP_PRECOMPILED,
    .len = OBCP_PRECOMPILED_LEN,
};


/* IO write test OBCP: exercises the obcpio.write function by sending
 * plain text, numeric conversions and string concatenation to the output.
 */
static const Harness_ObcpDef OBCP_IOTEST = {
   .id  = {'I','O','T','S','T'},
   .src =
      "import obcpio\n"
      "obcpio.write('IO test: single-line write\\n')\n"
      "obcpio.write('IO test: numeric value: ' + str(42) + '\\n')\n"
      "obcpio.write('IO test: ' + 'string ' + 'concatenation\\n')\n"
};

/* Datapool test OBCP: exercises write and read of int, enum, float and bool
 * parameters using the MicroPython obcpdatapool module.  Parameter IDs:
 *   1 = integer   2 = enum   3 = float   4 = bool   5 = success flag
 */
#define DPTEST_SUCCESS_PARAM_ID  5

static const Harness_ObcpDef OBCP_DPTEST = {
   .id  = {'D','P','T','S','T'},
   .src =
      "import obcpdatapool\n"
      "import obcpio\n"
      "obcpdatapool.writeintparameter(1, -42)\n"
      "v = obcpdatapool.readintparameter(1)\n"
      "if v != -42: raise RuntimeError('int fail')\n"
      "obcpio.write('DP int OK: ' + str(v) + '\\n')\n"
      "obcpdatapool.writeenumparameter(2, 7)\n"
      "v = obcpdatapool.readenumparameter(2)\n"
      "if v != 7: raise RuntimeError('enum fail')\n"
      "obcpio.write('DP enum OK: ' + str(v) + '\\n')\n"
      "obcpdatapool.writefloatparameter(3, 2.718)\n"
      "v = obcpdatapool.readfloatparameter(3)\n"
      "if abs(v - 2.718) > 0.001: raise RuntimeError('float fail')\n"
      "obcpio.write('DP float OK: ' + str(v) + '\\n')\n"
      "obcpdatapool.writeboolparameter(4, True)\n"
      "v = obcpdatapool.readboolparameter(4)\n"
      "if not v: raise RuntimeError('bool fail')\n"
      "obcpio.write('DP bool OK: ' + str(v) + '\\n')\n"
      "obcpdatapool.writeintparameter(5, 1)\n"
};

/* Events test OBCP: sends a known sequence of events via obcpevents.sendevent.
 * The harness verifies that all three events arrive in the expected order.
 * Event IDs: 101, 202, 303
 */
static const Harness_ObcpDef OBCP_EVTEST = {
   .id  = {'E','V','T','S','T'},
   .src =
      "import obcpevents\n"
      "obcpevents.sendevent(101)\n"
      "obcpevents.sendevent(202)\n"
      "obcpevents.sendevent(303)\n"
};

static const Harness_ObcpDef OBCP_TEST1 = {
   .id  = {'T','E','S','T','1'},
   .src = "import obcptime\nobcptime.wait(3000)\n"
};

static const Harness_ObcpDef OBCP_TEST2 = {
   .id  = {'T','E','S','T','2'},
   .src = "import obcptime\nobcptime.wait(5000)\n"
};

static const Harness_ObcpDef OBCP_TEST3 = {
   .id  = {'T','E','S','T','3'},
   .src = "import obcptime\nobcptime.wait(3000)\n"
};

static bool concurrency_test12_overlap_seen = false;
static bool concurrency_test23_overlap_seen = false;
static unsigned abort_test_wait_ticks = 0u;

#define ABORTTEST_WAIT_TIMEOUT_TICKS  2u

#define LOAD_LIMIT_TEST_MAX_OBCPS     32u

/* Gettime test OBCP: records the time before and after a known wait period,
 * stores the elapsed milliseconds and a pass/fail flag in the datapool.
 * Parameter IDs: 10 = elapsed milliseconds (int), 11 = passed (int: 1=pass)
 * Tolerance window: ±200 ms around the nominal 2000 ms wait.
 */
#define TIMETEST_WAIT_MS       2000
#define TIMETEST_TOLERANCE_MS   200
#define TIMETEST_ELAPSED_PARAM_ID  10
#define TIMETEST_PASSED_PARAM_ID   11

static const Harness_ObcpDef OBCP_TIMETEST = {
   .id  = {'T','I','M','E','T'},
   .src =
      "import obcptime\n"
      "import obcpdatapool\n"
      "import obcpio\n"
      "t0 = obcptime.gettime()\n"
      "obcptime.wait(2000)\n"
      "t1 = obcptime.gettime()\n"
      "elapsed = (t1[0] - t0[0]) * 1000 + (t1[1] - t0[1])\n"
      "obcpdatapool.writeintparameter(10, elapsed)\n"
      "passed = 1 if 1800 <= elapsed <= 2200 else 0\n"
      "obcpdatapool.writeintparameter(11, passed)\n"
      "obcpio.write('Gettime test: elapsed=' + str(elapsed) + 'ms, passed=' + str(passed) + '\\n')\n"
};

/* Packet receive test OBCP: runs concurrently with OBCP_PKTSEND.
 * Tests:
 *  - ispacketavailable / getchannelwithpacketavailable / non-blocking receivepacket
 *  - Timed receive (500 ms) of a 4-byte env-injected packet on channel 0
 *  - Sending an 8-byte reply to OBCP_PKTSEND on channel 1
 * Results are stored in the datapool (params 20 and 22).
 */
static const Harness_ObcpDef OBCP_PKTRECV = {
   .id  = {'P','K','T','R','V'},
   .src =
      "import obcppackets\n"
      "import obcpdatapool\n"
      "no_avail = 0 if obcppackets.ispacketavailable(3) else 1\n"
      "first_chan = obcppackets.getchannelwithpacketavailable()\n"
      "first_avail_ok = 1 if first_chan == 0 else 0\n"
      "none_pkt = obcppackets.receivepacket(3, 0)\n"
      "none_ok = 1 if none_pkt is None else 0\n"
      "obcpdatapool.writeintparameter(22, 1 if (no_avail and first_avail_ok and none_ok) else 0)\n"
      "pkt = obcppackets.receivepacket(0, 500)\n"
      "if pkt is not None and len(pkt) == 4 and pkt[0] == 0xAA and pkt[3] == 0xDD:\n"
      "    obcpdatapool.writeintparameter(20, 1)\n"
      "else:\n"
      "    obcpdatapool.writeintparameter(20, 0)\n"
      "obcppackets.sendpacket(1, bytes([0x11,0x22,0x33,0x44,0x55,0x66,0x77,0x88]))\n"
};

/* Packet send test OBCP: runs concurrently with OBCP_PKTRECV.
 * Tests:
 *  - cansendpacket with a valid channel (2) and an out-of-range channel (99)
 *  - Blocking receive (UINT32_MAX timeout) of the 8-byte packet from OBCP_PKTRECV
 *  - Sending a 16-byte packet to the environment on channel 2
 * Results are stored in the datapool (params 21 and 23).
 */
static const Harness_ObcpDef OBCP_PKTSEND = {
   .id  = {'P','K','T','S','D'},
   .src =
      "import obcppackets\n"
      "import obcpdatapool\n"
      "can_valid = 1 if obcppackets.cansendpacket(2) else 0\n"
      "can_invalid = 0 if obcppackets.cansendpacket(99) else 1\n"
      "obcpdatapool.writeintparameter(23, 1 if (can_valid and can_invalid) else 0)\n"
      "pkt = obcppackets.receivepacket(1, 4294967295)\n"
      "if pkt is not None and len(pkt) == 8 and pkt[0] == 0x11 and pkt[7] == 0x88:\n"
      "    obcpdatapool.writeintparameter(21, 1)\n"
      "else:\n"
      "    obcpdatapool.writeintparameter(21, 0)\n"
      "obcppackets.sendpacket(2, bytes([0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,"
                                       "0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF]))\n"
};

/* Step test OBCP: executes six numbered steps using obcpcontrol.beginstep /
 * endstep.  Steps 1-3 complete immediately; step 4 blocks inside beginstep
 * until the harness sets STEPTEST_UNBLOCK_PARAM_ID (30) to 1 in the
 * datapool; steps 5-6 complete immediately.  The OBCP records each begun
 * step number in STEPTEST_REACHED_STEP_PARAM_ID (31) and writes 1 to
 * STEPTEST_DONE_PARAM_ID (32) when all steps have finished.
 */
static const Harness_ObcpDef OBCP_STEPTEST = {
   .id  = {'S','T','P','T','S'},
   .src =
      "import obcpcontrol\n"
      "import obcpdatapool\n"
      "import obcptime\n"
      "obcpcontrol.beginstep(1)\n"
      "obcpdatapool.writeintparameter(31, 1)\n"
      "obcpcontrol.endstep(1, True)\n"
      "obcpcontrol.beginstep(2)\n"
      "obcpdatapool.writeintparameter(31, 2)\n"
      "obcpcontrol.endstep(2, True)\n"
      "obcpcontrol.beginstep(3)\n"
      "obcpdatapool.writeintparameter(31, 3)\n"
      "obcpcontrol.endstep(3, True)\n"
      "obcpcontrol.beginstep(4)\n"
      "obcpdatapool.writeintparameter(31, 4)\n"
      "while obcpdatapool.readintparameter(30) == 0:\n"
      "    obcptime.wait(10)\n"
      "obcpcontrol.endstep(4, True)\n"
      "obcpcontrol.beginstep(5)\n"
      "obcpdatapool.writeintparameter(31, 5)\n"
      "obcpcontrol.endstep(5, True)\n"
      "obcpcontrol.beginstep(6)\n"
      "obcpdatapool.writeintparameter(31, 6)\n"
      "obcpcontrol.endstep(6, True)\n"
      "obcpdatapool.writeintparameter(32, 1)\n"
};

/* Abort test OBCP: runs an infinite loop and never terminates on its own.
 * The harness polls until active_and_running, calls abort_obcp, then verifies
 * that the OBCP transitions back to inactive.
 */
static const Harness_ObcpDef OBCP_ABORTTEST = {
   .id  = {'A','B','R','T','T'},
   .src =
      "import obcptime\n"
      "while True:\n"
      "    obcptime.wait(10)\n"
};

/* Stop test OBCP: five steps with datapool writes; step 2 blocks until the
 * harness sets STOPTEST_UNBLOCK_PARAM_ID (50) to 1.  The harness requests a
 * stop at step 3 while the OBCP is blocked in step 2.  After unblocking, the
 * OBCP finishes step 2, executes the body of step 3 (writing param 42), then
 * endstep(3) triggers the stop.  Steps 4-5 and the done flag must not run.
 */
static const Harness_ObcpDef OBCP_STOPTEST = {
   .id  = {'S','T','O','P','T'},
   .src =
      "import obcpcontrol\n"
      "import obcpdatapool\n"
      "import obcptime\n"
      "obcpcontrol.beginstep(1)\n"
      "obcpdatapool.writeintparameter(40, 1)\n"
      "obcpcontrol.endstep(1, True)\n"
      "obcpcontrol.beginstep(2)\n"
      "obcpdatapool.writeintparameter(41, 1)\n"
      "while obcpdatapool.readintparameter(50) == 0:\n"
      "    obcptime.wait(10)\n"
      "obcpcontrol.endstep(2, True)\n"
      "obcpcontrol.beginstep(3)\n"
      "obcpdatapool.writeintparameter(42, 1)\n"
      "obcpcontrol.endstep(3, True)\n"
      "obcpcontrol.beginstep(4)\n"
      "obcpdatapool.writeintparameter(43, 1)\n"
      "obcpcontrol.endstep(4, True)\n"
      "obcpcontrol.beginstep(5)\n"
      "obcpdatapool.writeintparameter(44, 1)\n"
      "obcpcontrol.endstep(5, True)\n"
      "obcpdatapool.writeintparameter(45, 1)\n"
};

/* -----------------------------------------------------------------------
 * Helpers
 * ----------------------------------------------------------------------- */

static bool load_obcp(const Harness_ObcpDef *def)
{
   asn1SccOBCP_Code code;
   const size_t len = strlen(def->src) + 1;

   if (len > sizeof(code.arr)) {
      harness_report_failure_and_exit("Could not load OBCP %.5s: source size %zu exceeds limit %zu\n",
                                      def->id,
                                      len,
                                      sizeof(code.arr));
      return false;
   }

   memcpy(code.arr, def->src, len);
   code.nCount = (int)len;

   asn1SccT_Boolean ok = FALSE;
   harness_RI_load_obcp(&def->id, &code, &ok);
   if (!ok) {
      harness_report_failure_and_exit("Could not load OBCP %.5s\n", def->id);
   }
   return (bool)ok;
}

static bool load_precompiled_obcp(const Harness_PrecompiledObcpDef *def)
{
   asn1SccOBCP_Code code;

   if (def->len > sizeof(code.arr)) {
      harness_report_failure_and_exit("Could not load precompiled OBCP %.5s: source size %zu exceeds limit %zu\n",
                                      def->id,
                                      def->len,
                                      sizeof(code.arr));
      return false;
   }

   memcpy(code.arr, def->code, def->len);
   code.nCount = (int)def->len;

   asn1SccT_Boolean ok = FALSE;
   harness_RI_load_obcp(&def->id, &code, &ok);
   if (!ok) {
      harness_report_failure_and_exit("Could not load precompiled OBCP %.5s\n", def->id);
   }
   return (bool)ok;
}

static bool activate_precompiled_obcp(const Harness_PrecompiledObcpDef *def)
{
   asn1SccT_Boolean ok = FALSE;
   harness_RI_activate_obcp(&def->id, &ok);
   if (!ok) {
      harness_report_failure_and_exit("Could not activate precompiled OBCP %.5s\n", def->id);
   }
   return (bool)ok;
}

static asn1SccOBCP_Execution_Status get_precompiled_status(const Harness_PrecompiledObcpDef *def)
{
   asn1SccOBCP_Execution_Status status = OBCP_Execution_Status_inactive;
   asn1SccOBCP_Step_Id step_id = 0;
   asn1SccT_Boolean ok = FALSE;
   harness_RI_get_obcp_status(&def->id, &status, &step_id, &ok);
   if (!ok) {
      harness_report_failure_and_exit("Could not get status for precompiled OBCP %.5s\n", def->id);
   }
   return status;
}

static void unload_precompiled_obcp(const Harness_PrecompiledObcpDef *def)
{
   asn1SccT_Boolean ok = FALSE;
   harness_RI_unload_obcp(&def->id, &ok);
   if (!ok) {
      harness_report_failure_and_exit("Could not unload precompiled OBCP %.5s\n", def->id);
   }
}

static bool activate_obcp(const Harness_ObcpDef *def)
{
   asn1SccT_Boolean ok = FALSE;
   harness_RI_activate_obcp(&def->id, &ok);
   if (!ok) {
      harness_report_failure_and_exit("Could not activate OBCP %.5s\n", def->id);
   }
   return (bool)ok;
}

static asn1SccOBCP_Execution_Status get_status(const Harness_ObcpDef *def)
{
   asn1SccOBCP_Execution_Status status = OBCP_Execution_Status_inactive;
   asn1SccOBCP_Step_Id step_id = 0;
   asn1SccT_Boolean ok = FALSE;
   harness_RI_get_obcp_status(&def->id, &status, &step_id, &ok);
   if (!ok) {
      harness_report_failure_and_exit("Could not get status for OBCP %.5s\n", def->id);
   }
   return status;
}

static asn1SccOBCP_Step_Id get_current_step(const Harness_ObcpDef *def)
{
   asn1SccOBCP_Execution_Status status = OBCP_Execution_Status_inactive;
   asn1SccOBCP_Step_Id step_id = 0;
   asn1SccT_Boolean ok = FALSE;
   harness_RI_get_obcp_status(&def->id, &status, &step_id, &ok);
   if (!ok) {
      harness_report_failure_and_exit("Could not get status for OBCP %.5s\n", def->id);
   }
   return step_id;
}

static void unload_obcp(const Harness_ObcpDef *def)
{
   asn1SccT_Boolean ok = FALSE;
   harness_RI_unload_obcp(&def->id, &ok);
   if (!ok) {
      harness_report_failure_and_exit("Could not unload OBCP %.5s\n", def->id);
   }
}

static bool abort_obcp(const Harness_ObcpDef *def)
{
   asn1SccT_Boolean ok = FALSE;
   harness_RI_abort_obcp(&def->id, &ok);
   if (!ok) {
      harness_error_printf("Could not abort OBCP %.5s\n", def->id);
   }
   return (bool)ok;
}

static bool stop_obcp_at(const Harness_ObcpDef *def,
                          asn1SccOBCP_Step_Id step_id)
{
   asn1SccT_Boolean ok = FALSE;
   harness_RI_stop_obcp(&def->id, &step_id, &ok);
   if (!ok) {
      harness_error_printf("Could not stop OBCP %.5s at step %u\n",
                           def->id, (unsigned)step_id);
   }
   return (bool)ok;
}

static void make_load_limit_test_id(unsigned index, asn1SccOBCP_Id id)
{
   id[0] = 'L';
   id[1] = 'M';
   id[2] = 'T';
   id[3] = (char)('0' + ((index / 10u) % 10u));
   id[4] = (char)('0' + (index % 10u));
}

static bool can_load_obcp_id(const asn1SccOBCP_Id *id)
{
   asn1SccT_Boolean ok = FALSE;

   harness_RI_can_obcp_be_loaded(id, &ok);
   return (bool)ok;
}

static bool try_load_obcp_id(const asn1SccOBCP_Id *id, const char *src)
{
   asn1SccOBCP_Code code;
   const size_t len = strlen(src) + 1u;
   asn1SccT_Boolean ok = FALSE;

   if (len > sizeof(code.arr)) {
      harness_error_printf("Load limit test FAILED: probe source size %zu exceeds limit %zu\n",
                           len,
                           sizeof(code.arr));
      return false;
   }

   memcpy(code.arr, src, len);
   code.nCount = (int)len;
   harness_RI_load_obcp(id, &code, &ok);

   return (bool)ok;
}

static bool try_unload_obcp_id(const asn1SccOBCP_Id *id)
{
   asn1SccT_Boolean ok = FALSE;

   harness_RI_unload_obcp(id, &ok);
   return (bool)ok;
}

static bool run_load_limit_test(void)
{
   static const char load_limit_test_src[] = "pass\n";
   asn1SccOBCP_Id loaded_ids[LOAD_LIMIT_TEST_MAX_OBCPS];
   unsigned loaded_count = 0u;
   bool limit_reached = false;
   bool extra_load_rejected = false;
   bool cleanup_ok = true;

   for (unsigned index = 0u; index < LOAD_LIMIT_TEST_MAX_OBCPS; ++index) {
      asn1SccOBCP_Id id;

      make_load_limit_test_id(index, id);
      if (!can_load_obcp_id(&id)) {
         limit_reached = true;
         break;
      }
      if (!try_load_obcp_id(&id, load_limit_test_src)) {
         harness_error_printf("Load limit test FAILED: could not load probe OBCP %.5s before limit was reached\n",
                              id);
         cleanup_ok = false;
         break;
      }

      memcpy(loaded_ids[loaded_count], id, sizeof(asn1SccOBCP_Id));
      loaded_count++;
   }

   if (limit_reached) {
      asn1SccOBCP_Id extra_id;

      make_load_limit_test_id(loaded_count, extra_id);
      extra_load_rejected = !can_load_obcp_id(&extra_id) &&
                            !try_load_obcp_id(&extra_id, load_limit_test_src);
   }

   for (unsigned index = 0u; index < loaded_count; ++index) {
      if (!try_unload_obcp_id(&loaded_ids[index])) {
         harness_error_printf("Load limit test FAILED: could not unload probe OBCP %.5s during cleanup\n",
                              loaded_ids[index]);
         cleanup_ok = false;
      }
   }

   if (!limit_reached) {
      harness_error_printf("Load limit test FAILED: no load limit reached within %u probe OBCPs\n",
                           LOAD_LIMIT_TEST_MAX_OBCPS);
   }

   if (limit_reached && !extra_load_rejected) {
      harness_error_printf("Load limit test FAILED: engine accepted an extra load beyond the discovered limit\n");
   }

   // Main makefile should declare OBCP_MAXIMUM_NUMBER_OF_LOADED_OBCPS as 12
   // 12 is hardcoded to verify that the declaration in the Makefile is the source of truth.
   if (loaded_count != 12)
   {
      harness_error_printf("Loaded OBCP count (%u) does not match the one configured in Makefile\n",
                           loaded_count);
   }

   if (limit_reached && extra_load_rejected && cleanup_ok && loaded_count == 12u) {
      printf("Load limit test PASSED: load limit reached after %u probe OBCPs and one extra load was rejected\n",
             loaded_count);
      return true;
   }

   return false;
}

/* -----------------------------------------------------------------------
 * Test result table
 * ----------------------------------------------------------------------- */

typedef enum {
   TEST_NOT_RUN = 0,
   TEST_PASS,
   TEST_FAIL
} Harness_TestStatus;

typedef struct {
   const char        *name;
   Harness_TestStatus status;
} Harness_TestResult;

typedef enum {
   T_IO_WRITE        = 0,
   T_DATAPOOL,
   T_EVENTS,
   T_STEP_CONTROL,
   T_CONCURRENCY,
   T_GETTIME,
   T_PKT_ENV_RECV,
   T_PKT_INTER_OBCP,
   T_PKT_NONBLOCKING,
   T_PKT_CANSEND,
   T_PKT_ENV_SEND,
   T_ABORT,
   T_STOP,
   T_PRECOMPILED,
   T_LOAD_LIMIT,
   T_COUNT
} Harness_TestIndex;

static Harness_TestResult test_results[T_COUNT] = {
   [T_IO_WRITE]        = { "IO write output",                          TEST_NOT_RUN },
   [T_DATAPOOL]        = { "Datapool read/write (int/enum/float/bool)", TEST_NOT_RUN },
   [T_EVENTS]          = { "Events sequence",                          TEST_NOT_RUN },
   [T_STEP_CONTROL]    = { "Step control (beginstep/endstep)",         TEST_NOT_RUN },
   [T_CONCURRENCY]     = { "Concurrent OBCP execution",                TEST_NOT_RUN },
   [T_GETTIME]         = { "Gettime accuracy",                         TEST_NOT_RUN },
   [T_PKT_ENV_RECV]    = { "Packet: Env->OBCP receive (timed)",        TEST_NOT_RUN },
   [T_PKT_INTER_OBCP]  = { "Packet: OBCP-to-OBCP exchange",           TEST_NOT_RUN },
   [T_PKT_NONBLOCKING] = { "Packet: non-blocking + availability",      TEST_NOT_RUN },
   [T_PKT_CANSEND]     = { "Packet: cansendpacket",                    TEST_NOT_RUN },
   [T_PKT_ENV_SEND]    = { "Packet: OBCP->Env send",                   TEST_NOT_RUN },
   [T_ABORT]           = { "Abort OBCP (terminates infinite loop)",    TEST_NOT_RUN },
   [T_STOP]            = { "Stop OBCP at endstep boundary",            TEST_NOT_RUN },
   [T_PRECOMPILED]     = { "Precompiled OBCP bytecode",                TEST_NOT_RUN },
   [T_LOAD_LIMIT]      = { "Loaded OBCP limit",                        TEST_NOT_RUN },
};

static void test_record(Harness_TestIndex idx, bool passed)
{
   test_results[idx].status = passed ? TEST_PASS : TEST_FAIL;
}

static void report_final_results(void)
{
   static const char * const status_str[] = { "NOT RUN", "PASS   ", "FAIL   " };
   bool all_pass = true;
   printf("\n========================================\n");
   printf(" Test Results\n");
   printf("========================================\n");
   for (int i = 0; i < T_COUNT; i++) {
      const Harness_TestStatus s = test_results[i].status;
      if (s != TEST_PASS) { all_pass = false; }
      printf("  [%s] %s\n", status_str[s], test_results[i].name);
   }
   printf("----------------------------------------\n");
   printf("  Overall: %s\n", all_pass ? "PASS" : "FAIL");
   printf("========================================\n");
}

/* -----------------------------------------------------------------------
 * Trigger state machine
 * ----------------------------------------------------------------------- */

typedef enum {
   PHASE_INIT,
   PHASE_IO_WRITE_TEST,
   PHASE_DATAPOOL_TEST,
   PHASE_EVENTS_TEST,
   PHASE_STEP_TEST_WAIT_STEP4,
   PHASE_STEP_TEST_COMPLETE,
   PHASE_CONCURRENCY_WAIT_TEST1,
   PHASE_CONCURRENCY_ALL_RUNNING,
   PHASE_GETTIME_TEST,
   PHASE_PACKETS_INIT,
   PHASE_PACKETS_RUNNING,
   PHASE_ABORT_TEST_RUNNING,
   PHASE_ABORT_TEST_WAIT,
   PHASE_STOP_TEST_RUNNING,
   PHASE_STOP_TEST_WAIT,
   PHASE_PRECOMPILED_TEST,
} Harness_Phase;

static Harness_Phase harness_phase = PHASE_INIT;
static Harness_Phase harness_phase_timeout_phase = PHASE_INIT;
static uint64_t      harness_phase_started_ns = 0ULL;

#define HARNESS_PHASE_TIMEOUT_NS 20000000000ULL

static Harness_Phase harness_get_phase(void)
{
   return harness_phase;
}

static void harness_set_phase(Harness_Phase phase)
{
   harness_phase = phase;
}

static bool harness_phase_has_timeout(Harness_Phase phase)
{
   return phase != PHASE_INIT;
}

static void harness_record_phase_timeout(Harness_Phase phase)
{
   switch (phase) {
      case PHASE_IO_WRITE_TEST:
         test_record(T_IO_WRITE, false);
         break;
      case PHASE_DATAPOOL_TEST:
         test_record(T_DATAPOOL, false);
         break;
      case PHASE_EVENTS_TEST:
         test_record(T_EVENTS, false);
         break;
      case PHASE_STEP_TEST_WAIT_STEP4:
      case PHASE_STEP_TEST_COMPLETE:
         test_record(T_STEP_CONTROL, false);
         break;
      case PHASE_CONCURRENCY_WAIT_TEST1:
      case PHASE_CONCURRENCY_ALL_RUNNING:
         test_record(T_CONCURRENCY, false);
         break;
      case PHASE_GETTIME_TEST:
         test_record(T_GETTIME, false);
         break;
      case PHASE_PACKETS_INIT:
      case PHASE_PACKETS_RUNNING:
         test_record(T_PKT_ENV_RECV, false);
         test_record(T_PKT_INTER_OBCP, false);
         test_record(T_PKT_NONBLOCKING, false);
         test_record(T_PKT_CANSEND, false);
         test_record(T_PKT_ENV_SEND, false);
         break;
      case PHASE_ABORT_TEST_RUNNING:
      case PHASE_ABORT_TEST_WAIT:
         test_record(T_ABORT, false);
         break;
      case PHASE_STOP_TEST_RUNNING:
      case PHASE_STOP_TEST_WAIT:
         test_record(T_STOP, false);
         break;
      case PHASE_PRECOMPILED_TEST:
         test_record(T_PRECOMPILED, false);
         break;
      default:
         break;
   }
}

/* This function is not broken down on purpose, as the tests execute
   phase by phase, semi-asynchronously.
   Each test is usually broken down the following way:
   - state N -> initialization,
   - state N+1 -> verification.
   As a consequence, in state N+1:
   - test N is being verified,
   - test N + 1 is being started.
   Partial verification is sometimes done in provided interfaces 
   (e.g., event or write counting).
   In such case, trigger verifies the partial results.
   */
void harness_PI_trigger(void)
{
   const Harness_Phase phase = harness_get_phase();
   const uint64_t now_ns = Hal_GetElapsedTimeInNs();

   if (phase != harness_phase_timeout_phase) {
      harness_phase_timeout_phase = phase;
      harness_phase_started_ns = now_ns;
   } else if (harness_phase_has_timeout(phase) &&
              now_ns - harness_phase_started_ns >= HARNESS_PHASE_TIMEOUT_NS) {
      harness_record_phase_timeout(phase);
      harness_report_failure_and_exit("Harness FAILED: phase %d timed out after %llu ns\n",
                                      (int)phase,
                                      (unsigned long long)(now_ns - harness_phase_started_ns));
      return;
   }

   switch (phase) {

      /* -----------------------------------------------------------------
       * Start the engine and kick off the IO write test OBCP.
       * ----------------------------------------------------------------- */
      case PHASE_INIT: {
         harness_RI_start_obcp_engine();

         harness_lock_state();
         io_write_test_active = true;
         io_test_msg_index = 0;
         io_write_test_all_ok = true;
         harness_unlock_state();

         if (!load_obcp(&OBCP_IOTEST)) return;
         if (!activate_obcp(&OBCP_IOTEST)) return;

         printf("IO write test OBCP activated\n");
         harness_set_phase(PHASE_IO_WRITE_TEST);
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the IO write test OBCP to complete, then kick off the
       * datapool test OBCP.
       * ----------------------------------------------------------------- */
      case PHASE_IO_WRITE_TEST: {
         const asn1SccOBCP_Execution_Status sio = get_status(&OBCP_IOTEST);

         if (sio == OBCP_Execution_Status_inactive) {
            size_t io_test_count;
            bool io_test_ok;

            harness_lock_state();
            io_write_test_active = false;
            io_test_count = io_test_msg_index;
            io_test_ok = io_write_test_all_ok;
            harness_unlock_state();

            io_test_ok = io_test_ok && (io_test_count == IO_TEST_EXPECTED_COUNT);
            test_record(T_IO_WRITE, io_test_ok);
            if (io_test_count != IO_TEST_EXPECTED_COUNT) {
               harness_error_printf("IO test ERROR: expected %zu messages, received %zu\n",
                                    IO_TEST_EXPECTED_COUNT, io_test_count);
            } else if (io_test_ok) {
               printf("IO write tests finished — all %zu messages verified OK\n",
                      IO_TEST_EXPECTED_COUNT);
            }
            unload_obcp(&OBCP_IOTEST);

            {
               const asn1SccOBCP_Parameter_Id success_id = DPTEST_SUCCESS_PARAM_ID;
               asn1SccOBCP_Parameter_Value zero_val;
               zero_val.kind        = OBCP_Parameter_Value_int_value_PRESENT;
               zero_val.u.int_value = 0;
               harness_PI_set_parameter_value(&success_id, &zero_val);
            }

            if (!load_obcp(&OBCP_DPTEST)) return;
            if (!activate_obcp(&OBCP_DPTEST)) return;

            printf("Datapool test OBCP activated\n");
            harness_set_phase(PHASE_DATAPOOL_TEST);
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the datapool test OBCP to complete, then launch the
       * concurrency tests (TEST1 and TEST2 run in parallel).
       * ----------------------------------------------------------------- */
      case PHASE_DATAPOOL_TEST: {
         const asn1SccOBCP_Execution_Status sdp = get_status(&OBCP_DPTEST);

         if (sdp == OBCP_Execution_Status_inactive) {
            const asn1SccOBCP_Parameter_Id success_id = DPTEST_SUCCESS_PARAM_ID;
            const asn1SccOBCP_Parameter_Type int_type = OBCP_Parameter_Type_integer_type;
            asn1SccOBCP_Parameter_Value success_val;

            harness_PI_get_parameter_value(&success_id, &int_type, &success_val);

            const bool datapool_ok =
               success_val.kind == OBCP_Parameter_Value_int_value_PRESENT &&
               success_val.u.int_value == 1;

            test_record(T_DATAPOOL, datapool_ok);
            if (datapool_ok) {
               printf("Datapool tests finished\n");
            } else {
               harness_error_printf("Datapool test FAILED: success flag param %u value=%d\n",
                                    (unsigned)success_id,
                                    success_val.kind == OBCP_Parameter_Value_int_value_PRESENT ?
                                       (int)success_val.u.int_value : -1);
            }
            unload_obcp(&OBCP_DPTEST);

            if (!load_obcp(&OBCP_EVTEST)) return;
            harness_lock_state();
            events_test_active         = true;
            events_test_received_count = 0;
            events_test_all_ok         = true;
            harness_unlock_state();
            if (!activate_obcp(&OBCP_EVTEST)) return;

            printf("Events test OBCP activated\n");
            harness_set_phase(PHASE_EVENTS_TEST);
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the events test OBCP to complete, then verify that all
       * expected events were received, and launch the concurrency tests.
       * ----------------------------------------------------------------- */
      case PHASE_EVENTS_TEST: {
         const asn1SccOBCP_Execution_Status sev = get_status(&OBCP_EVTEST);

         if (sev == OBCP_Execution_Status_inactive) {
            bool events_ok_order;
            size_t events_count;

            harness_lock_state();
            events_test_active = false;
            events_ok_order = events_test_all_ok;
            events_count = events_test_received_count;
            harness_unlock_state();

            const bool events_ok = events_ok_order &&
                                   events_count == EVENTS_TEST_EXPECTED_COUNT;
            test_record(T_EVENTS, events_ok);
            if (!events_ok) {
               harness_error_printf("Events test FAILED: expected %zu events, received %zu%s\n",
                                    EVENTS_TEST_EXPECTED_COUNT,
                                    events_count,
                                    events_ok_order ? "" : " (order/ID mismatch)");
            } else {
               printf("Events test PASSED: all %zu events received in correct order\n",
                      EVENTS_TEST_EXPECTED_COUNT);
            }
            unload_obcp(&OBCP_EVTEST);

            /* Initialise step test datapool entries to zero before loading */
            {
               const asn1SccOBCP_Parameter_Id unblock_id = STEPTEST_UNBLOCK_PARAM_ID;
               const asn1SccOBCP_Parameter_Id reached_id = STEPTEST_REACHED_STEP_PARAM_ID;
               const asn1SccOBCP_Parameter_Id done_id    = STEPTEST_DONE_PARAM_ID;
               asn1SccOBCP_Parameter_Value zero_val;
               zero_val.kind        = OBCP_Parameter_Value_int_value_PRESENT;
               zero_val.u.int_value = 0;
               harness_PI_set_parameter_value(&unblock_id, &zero_val);
               harness_PI_set_parameter_value(&reached_id, &zero_val);
               harness_PI_set_parameter_value(&done_id,    &zero_val);
            }

            if (!load_obcp(&OBCP_STEPTEST)) return;
            if (!activate_obcp(&OBCP_STEPTEST)) return;

            printf("Step test OBCP activated\n");
            harness_set_phase(PHASE_STEP_TEST_WAIT_STEP4);
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Poll until the OBCP reports that step 4 has begun, confirm it,
       * then unblock the OBCP by setting the unblock datapool parameter.
       * ----------------------------------------------------------------- */
      case PHASE_STEP_TEST_WAIT_STEP4: {
         const asn1SccOBCP_Step_Id current_step = get_current_step(&OBCP_STEPTEST);

         if (current_step == STEPTEST_BLOCKING_STEP) {
            printf("Step test: get_obcp_status reports step %u active — unblocking OBCP\n",
                   (unsigned)current_step);
            const asn1SccOBCP_Parameter_Id unblock_id = STEPTEST_UNBLOCK_PARAM_ID;
            asn1SccOBCP_Parameter_Value one_val;
            one_val.kind        = OBCP_Parameter_Value_int_value_PRESENT;
            one_val.u.int_value = 1;
            harness_PI_set_parameter_value(&unblock_id, &one_val);
            harness_set_phase(PHASE_STEP_TEST_COMPLETE);
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the step test OBCP to finish, then verify that all
       * steps were executed and launch the concurrency tests.
       * ----------------------------------------------------------------- */
      case PHASE_STEP_TEST_COMPLETE: {
         const asn1SccOBCP_Execution_Status ss = get_status(&OBCP_STEPTEST);

         if (ss == OBCP_Execution_Status_inactive) {
            const asn1SccOBCP_Parameter_Type int_type  = OBCP_Parameter_Type_integer_type;
            asn1SccOBCP_Parameter_Value v;
            const asn1SccOBCP_Parameter_Id reached_id = STEPTEST_REACHED_STEP_PARAM_ID;
            const asn1SccOBCP_Parameter_Id done_id    = STEPTEST_DONE_PARAM_ID;

            harness_PI_get_parameter_value(&reached_id, &int_type, &v);
            const int32_t last_step = v.u.int_value;
            harness_PI_get_parameter_value(&done_id, &int_type, &v);
            const bool steps_done = (v.u.int_value == 1);

            const bool step_ok = steps_done && last_step == STEPTEST_LAST_STEP;
            test_record(T_STEP_CONTROL, step_ok);
            if (step_ok) {
               printf("Step test PASSED: all %d steps completed, "
                      "step %d hold-and-release verified\n",
                      STEPTEST_LAST_STEP, STEPTEST_BLOCKING_STEP);
            } else {
               harness_error_printf("Step test FAILED: steps_done=%d, last_step=%d "
                                    "(expected %d)\n",
                                    (int)steps_done, (int)last_step, STEPTEST_LAST_STEP);
            }

            unload_obcp(&OBCP_STEPTEST);

            if (!load_obcp(&OBCP_TEST1)) return;
            if (!load_obcp(&OBCP_TEST2)) return;
            if (!load_obcp(&OBCP_TEST3)) return;

            concurrency_test12_overlap_seen = false;
            concurrency_test23_overlap_seen = false;

            /* TEST1 and TEST2 start immediately; TEST3 waits for TEST1 */
            if (!activate_obcp(&OBCP_TEST1)) return;
            if (!activate_obcp(&OBCP_TEST2)) return;

            printf("TEST1 (3 s) and TEST2 (5 s) activated\n");
            harness_set_phase(PHASE_CONCURRENCY_WAIT_TEST1);
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for TEST1 to complete, then activate TEST3 to exercise
       * concurrent execution of two active OBCPs.
       * ----------------------------------------------------------------- */
      case PHASE_CONCURRENCY_WAIT_TEST1: {
         const asn1SccOBCP_Execution_Status s1 = get_status(&OBCP_TEST1);
         const asn1SccOBCP_Execution_Status s2 = get_status(&OBCP_TEST2);

         printf("Status — TEST1: %d  TEST2: %d\n",
                s1, s2);

         if (s1 == OBCP_Execution_Status_active_and_running &&
             s2 == OBCP_Execution_Status_active_and_running) {
            concurrency_test12_overlap_seen = true;
         }

         if (s1 == OBCP_Execution_Status_inactive) {
            printf("TEST1 finished — activating TEST3 (3 s)\n");
            unload_obcp(&OBCP_TEST1);
            if (!activate_obcp(&OBCP_TEST3)) return;
            harness_set_phase(PHASE_CONCURRENCY_ALL_RUNNING);
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for both remaining OBCPs to finish, then kick off the
       * gettime accuracy test.
       * ----------------------------------------------------------------- */
      case PHASE_CONCURRENCY_ALL_RUNNING: {
         const asn1SccOBCP_Execution_Status s2 = get_status(&OBCP_TEST2);
         const asn1SccOBCP_Execution_Status s3 = get_status(&OBCP_TEST3);

         printf("Status — TEST2: %d  TEST3: %d\n", s2, s3);

         if (s2 == OBCP_Execution_Status_active_and_running &&
             s3 == OBCP_Execution_Status_active_and_running) {
            concurrency_test23_overlap_seen = true;
         }

         if (s2 == OBCP_Execution_Status_inactive &&
             s3 == OBCP_Execution_Status_inactive)
         {
            const bool concurrency_ok = concurrency_test12_overlap_seen &&
                                        concurrency_test23_overlap_seen;

            test_record(T_CONCURRENCY, concurrency_ok);
            if (concurrency_ok) {
               printf("Concurrency test PASSED: TEST1/TEST2 and TEST2/TEST3 overlapped in active execution\n");
            } else {
               harness_error_printf("Concurrency test FAILED: overlap observed TEST1/TEST2=%d, TEST2/TEST3=%d\n",
                                    (int)concurrency_test12_overlap_seen,
                                    (int)concurrency_test23_overlap_seen);
            }
            unload_obcp(&OBCP_TEST2);
            unload_obcp(&OBCP_TEST3);

            if (!load_obcp(&OBCP_TIMETEST)) return;
            if (!activate_obcp(&OBCP_TIMETEST)) return;

            printf("Gettime test OBCP activated (waiting %d ms)\n",
                   TIMETEST_WAIT_MS);
            harness_set_phase(PHASE_GETTIME_TEST);
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the gettime test OBCP to complete, then read the
       * elapsed time and pass/fail flag from the datapool and report.
       * ----------------------------------------------------------------- */
      case PHASE_GETTIME_TEST: {
         const asn1SccOBCP_Execution_Status st = get_status(&OBCP_TIMETEST);

         if (st == OBCP_Execution_Status_inactive) {
            /* Read results written by the OBCP into the datapool */
            const asn1SccOBCP_Parameter_Id elapsed_id = TIMETEST_ELAPSED_PARAM_ID;
            const asn1SccOBCP_Parameter_Id passed_id  = TIMETEST_PASSED_PARAM_ID;
            const asn1SccOBCP_Parameter_Type int_type  = OBCP_Parameter_Type_integer_type;
            asn1SccOBCP_Parameter_Value elapsed_val, passed_val;

            harness_PI_get_parameter_value(&elapsed_id, &int_type, &elapsed_val);
            harness_PI_get_parameter_value(&passed_id,  &int_type, &passed_val);

            const int32_t elapsed_ms = elapsed_val.u.int_value;
            const int32_t passed     = passed_val.u.int_value;

            test_record(T_GETTIME, passed != 0);
            if (passed) {
               printf("Gettime test PASSED: elapsed=%d ms "
                      "(nominal=%d ms, tolerance=\u00b1%d ms)\n",
                      elapsed_ms, TIMETEST_WAIT_MS, TIMETEST_TOLERANCE_MS);
            } else {
               harness_error_printf("Gettime test FAILED: elapsed=%d ms "
                                    "(expected %d\u00b1%d ms)\n",
                                    elapsed_ms, TIMETEST_WAIT_MS, TIMETEST_TOLERANCE_MS);
            }

            printf("Gettime test finished\n");
            unload_obcp(&OBCP_TIMETEST);
            harness_set_phase(PHASE_PACKETS_INIT);
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Pre-inject the env-input packet on channel 0, then activate
       * OBCP_PKTRECV and OBCP_PKTSEND concurrently.
       * ----------------------------------------------------------------- */
      case PHASE_PACKETS_INIT: {
         /* Inject a 4-byte packet from the environment into channel 0.
          * OBCP_PKTRECV will pick it up with a timed receivepacket(). */
         const asn1SccOBCP_Channel_Id ch0 = PKTTEST_ENV_INPUT_CHANNEL;
         asn1SccOBCP_Packet env_in;
         memset(&env_in, 0, sizeof(env_in));
         env_in.arr[0] = (byte)0xAA;
         env_in.arr[1] = (byte)0xBB;
         env_in.arr[2] = (byte)0xCC;
         env_in.arr[3] = (byte)0xDD;
         env_in.nCount = 4;
         asn1SccT_Boolean receive_success = FALSE;
         const uint64_t deadline_ns = Hal_GetElapsedTimeInNs() + HARNESS_PACKET_RETRY_TIMEOUT_NS;
         while (!receive_success)
         {
            harness_RI_receive_packet(&ch0, &env_in, &receive_success);
            if (!receive_success) {
               if (Hal_GetElapsedTimeInNs() >= deadline_ns) {
                  harness_record_phase_timeout(PHASE_PACKETS_INIT);
                  harness_report_failure_and_exit("Packets test FAILED: timed out injecting env-input packet on channel 0\n");
                  return;
               }
               (void)Hal_SleepNs(HARNESS_PACKET_RETRY_SLEEP_NS);
            }
         }
         printf("Packets test: injected 4-byte env-input packet on channel 0\n");

         harness_lock_state();
         pkttest_active              = true;
         pkttest_env_output_received = false;
         harness_unlock_state();

         if (!load_obcp(&OBCP_PKTRECV)) return;
         if (!load_obcp(&OBCP_PKTSEND)) return;
         if (!activate_obcp(&OBCP_PKTRECV)) return;
         if (!activate_obcp(&OBCP_PKTSEND)) return;

         printf("Packets test OBCPs activated (PKTRECV + PKTSEND running concurrently)\n");
         harness_set_phase(PHASE_PACKETS_RUNNING);
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for both packet OBCPs to complete, then read datapool results
       * and verify all aspects of the packets test.
       * ----------------------------------------------------------------- */
      case PHASE_PACKETS_RUNNING: {
         const asn1SccOBCP_Execution_Status sr = get_status(&OBCP_PKTRECV);
         const asn1SccOBCP_Execution_Status ss = get_status(&OBCP_PKTSEND);

         if (sr == OBCP_Execution_Status_inactive &&
             ss == OBCP_Execution_Status_inactive)
         {
            bool env_output_received;
            asn1SccOBCP_Packet env_output_packet;

            harness_lock_state();
            pkttest_active = false;
            env_output_received = pkttest_env_output_received;
            env_output_packet = pkttest_env_output_packet;
            harness_unlock_state();

            /* Read all four in-OBCP test outcomes from the datapool */
            const asn1SccOBCP_Parameter_Type int_type = OBCP_Parameter_Type_integer_type;
            asn1SccOBCP_Parameter_Value v;
            const asn1SccOBCP_Parameter_Id env_recv_id  = PKTTEST_ENV_RECEIVE_PARAM_ID;
            const asn1SccOBCP_Parameter_Id inter_id     = PKTTEST_INTER_OBCP_PARAM_ID;
            const asn1SccOBCP_Parameter_Id nonblock_id  = PKTTEST_NONBLOCKING_PARAM_ID;
            const asn1SccOBCP_Parameter_Id cansend_id   = PKTTEST_CANSEND_PARAM_ID;

            harness_PI_get_parameter_value(&env_recv_id,  &int_type, &v);
            const bool env_recv_ok  = (v.u.int_value == 1);
            harness_PI_get_parameter_value(&inter_id,     &int_type, &v);
            const bool inter_ok     = (v.u.int_value == 1);
            harness_PI_get_parameter_value(&nonblock_id,  &int_type, &v);
            const bool nonblock_ok  = (v.u.int_value == 1);
            harness_PI_get_parameter_value(&cansend_id,   &int_type, &v);
            const bool cansend_ok   = (v.u.int_value == 1);

            /* Verify the 16-byte packet sent from OBCP_PKTSEND to environment */
            bool env_out_ok = env_output_received &&
                              (env_output_packet.nCount == 16);
            if (env_out_ok) {
               for (int i = 0; i < 16; i++) {
                  if ((unsigned char)env_output_packet.arr[i] !=
                      pkttest_expected_env_output[i]) {
                     env_out_ok = false;
                     break;
                  }
               }
            }

            test_record(T_PKT_ENV_RECV,    env_recv_ok);
            test_record(T_PKT_INTER_OBCP,  inter_ok);
            test_record(T_PKT_NONBLOCKING, nonblock_ok);
            test_record(T_PKT_CANSEND,     cansend_ok);
            test_record(T_PKT_ENV_SEND,    env_out_ok);
            printf("Packets test results:\n");
            printf("  Env\u2192OBCP receive  (ch0, 4 B, 500 ms timeout): %s\n",
                   env_recv_ok ? "PASSED" : "FAILED");
            printf("  OBCP-to-OBCP exchange (ch0\u21921, 8 B, blocking):  %s\n",
                   inter_ok    ? "PASSED" : "FAILED");
            printf("  Non-blocking + availability checks (ch3):      %s\n",
                   nonblock_ok ? "PASSED" : "FAILED");
            printf("  cansendpacket (valid ch2 / invalid ch99):       %s\n",
                   cansend_ok  ? "PASSED" : "FAILED");
            printf("  OBCP\u2192Env send      (ch2, 16 B):                %s\n",
                   env_out_ok  ? "PASSED" : "FAILED");

            const bool all_ok = env_recv_ok && inter_ok && nonblock_ok &&
                                cansend_ok  && env_out_ok;
            printf("Packets test overall: %s\n", all_ok ? "PASSED" : "FAILED");
            if (!all_ok) {
               harness_error_printf("Packets test FAILED: one or more packet checks failed\n");
            }
            unload_obcp(&OBCP_PKTRECV);
            unload_obcp(&OBCP_PKTSEND);

            if (!load_obcp(&OBCP_ABORTTEST)) return;
            if (!activate_obcp(&OBCP_ABORTTEST)) return;
            printf("Abort test OBCP activated (infinite loop)\n");
            harness_set_phase(PHASE_ABORT_TEST_RUNNING);
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Poll until the OBCP is actively running, then send abort.
       * ----------------------------------------------------------------- */
      case PHASE_ABORT_TEST_RUNNING: {
         const asn1SccOBCP_Execution_Status sa = get_status(&OBCP_ABORTTEST);
         if (sa == OBCP_Execution_Status_active_and_running) {
            printf("Abort test: OBCP is active_and_running \u2014 sending abort\n");
            abort_obcp(&OBCP_ABORTTEST);
            abort_test_wait_ticks = 0u;
            harness_set_phase(PHASE_ABORT_TEST_WAIT);
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the aborted OBCP to reach inactive, then launch the
       * stop test.
       * ----------------------------------------------------------------- */
      case PHASE_ABORT_TEST_WAIT: {
         bool start_next_test = false;
         const asn1SccOBCP_Execution_Status sa = get_status(&OBCP_ABORTTEST);
         if (sa == OBCP_Execution_Status_inactive) {
            test_record(T_ABORT, true);
            printf("Abort test PASSED: OBCP transitioned to inactive after abort\n");
            unload_obcp(&OBCP_ABORTTEST);
            start_next_test = true;
         } else {
            abort_test_wait_ticks++;
            if (abort_test_wait_ticks >= ABORTTEST_WAIT_TIMEOUT_TICKS) {
               test_record(T_ABORT, false);
               harness_error_printf("Abort test FAILED: OBCP did not reach inactive within %u trigger ticks after abort request\n",
                                    ABORTTEST_WAIT_TIMEOUT_TICKS);
               // Abort does not work, so unloading makes no sense. We should have enough remaining slots.
               start_next_test = true;
            }
         }
         if (start_next_test)
         {
            /* Initialise stop test datapool entries to zero */
            {
               asn1SccOBCP_Parameter_Value zero_val;
               zero_val.kind        = OBCP_Parameter_Value_int_value_PRESENT;
               zero_val.u.int_value = 0;
               asn1SccOBCP_Parameter_Id pid;
               for (pid = STOPTEST_STEP1_PARAM_ID;
                    pid <= STOPTEST_DONE_PARAM_ID; ++pid) {
                  harness_PI_set_parameter_value(&pid, &zero_val);
               }
               const asn1SccOBCP_Parameter_Id unblock_id = STOPTEST_UNBLOCK_PARAM_ID;
               harness_PI_set_parameter_value(&unblock_id, &zero_val);
            }

            if (!load_obcp(&OBCP_STOPTEST)) return;
            if (!activate_obcp(&OBCP_STOPTEST)) return;
            printf("Stop test OBCP activated\n");
            harness_set_phase(PHASE_STOP_TEST_RUNNING);
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait until the OBCP is blocked in step 2; request stop at step 3
       * then unblock so it advances to step 3 and the stop fires there.
       * ----------------------------------------------------------------- */
      case PHASE_STOP_TEST_RUNNING: {
         const asn1SccOBCP_Step_Id current_step = get_current_step(&OBCP_STOPTEST);
         if (current_step == STOPTEST_BLOCKING_STEP) {
            printf("Stop test: OBCP is in step %u \u2014 requesting stop at step %u\n",
                   (unsigned)current_step, (unsigned)STOPTEST_TARGET_STEP);
            stop_obcp_at(&OBCP_STOPTEST, STOPTEST_TARGET_STEP);
            const asn1SccOBCP_Parameter_Id unblock_id = STOPTEST_UNBLOCK_PARAM_ID;
            asn1SccOBCP_Parameter_Value one_val;
            one_val.kind        = OBCP_Parameter_Value_int_value_PRESENT;
            one_val.u.int_value = 1;
            harness_PI_set_parameter_value(&unblock_id, &one_val);
            harness_set_phase(PHASE_STOP_TEST_WAIT);
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the stopped OBCP to reach inactive, then verify that
       * steps 1-3 ran (params 40-42 == 1) and steps 4-5 did not
       * (params 43-45 == 0).
       * ----------------------------------------------------------------- */
      case PHASE_STOP_TEST_WAIT: {
         const asn1SccOBCP_Execution_Status ss = get_status(&OBCP_STOPTEST);
         if (ss == OBCP_Execution_Status_inactive) {
            const asn1SccOBCP_Parameter_Type int_type = OBCP_Parameter_Type_integer_type;
            asn1SccOBCP_Parameter_Value v;
            bool ok = true;
            asn1SccOBCP_Parameter_Id pid;

            /* Steps 1-3 body must have run (params 40-42 == 1) */
            for (pid = STOPTEST_STEP1_PARAM_ID;
                 pid <= STOPTEST_STEP3_PARAM_ID; ++pid) {
               harness_PI_get_parameter_value(&pid, &int_type, &v);
               if (v.u.int_value != 1) {
                  harness_error_printf("Stop test FAILED: param %u expected 1, got %d "
                                       "(step body before/at stop not executed)\n",
                                       (unsigned)pid, (int)v.u.int_value);
                  ok = false;
               }
            }

            /* Steps 4-5 and done flag must NOT have run (params 43-45 == 0) */
            for (pid = STOPTEST_STEP4_PARAM_ID;
                 pid <= STOPTEST_DONE_PARAM_ID; ++pid) {
               harness_PI_get_parameter_value(&pid, &int_type, &v);
               if (v.u.int_value != 0) {
                  harness_error_printf("Stop test FAILED: param %u expected 0, got %d "
                                       "(execution continued past stop step)\n",
                                       (unsigned)pid, (int)v.u.int_value);
                  ok = false;
               }
            }

            test_record(T_STOP, ok);
            if (ok) {
               printf("Stop test PASSED: OBCP stopped at endstep(%d); "
                      "steps 1-%d body executed, steps %d+ not reached\n",
                      STOPTEST_TARGET_STEP, STOPTEST_TARGET_STEP,
                      STOPTEST_TARGET_STEP + 1);
            }
            unload_obcp(&OBCP_STOPTEST);

            {
               const asn1SccOBCP_Parameter_Id precompiled_param_id = 42u;
               asn1SccOBCP_Parameter_Value zero_val;
               zero_val.kind        = OBCP_Parameter_Value_int_value_PRESENT;
               zero_val.u.int_value = 0;
               harness_PI_set_parameter_value(&precompiled_param_id, &zero_val);
            }

            if (!load_precompiled_obcp(&OBCP_PRECOMPILED_TEST)) return;
            if (!activate_precompiled_obcp(&OBCP_PRECOMPILED_TEST)) return;
            printf("Precompiled OBCP test activated\n");
            harness_set_phase(PHASE_PRECOMPILED_TEST);
         }
         break;
      }

      /* -----------------------------------------------------------------
       * Wait for the precompiled OBCP to finish, then verify that it wrote
       * datapool parameter 42 with value 1234 before running the load-limit
       * test and reporting final results.
       * ----------------------------------------------------------------- */
      case PHASE_PRECOMPILED_TEST: {
         const asn1SccOBCP_Execution_Status sp = get_precompiled_status(&OBCP_PRECOMPILED_TEST);

         if (sp == OBCP_Execution_Status_inactive) {
            const asn1SccOBCP_Parameter_Id precompiled_param_id = 42u;
            const asn1SccOBCP_Parameter_Type int_type = OBCP_Parameter_Type_integer_type;
            asn1SccOBCP_Parameter_Value value;

            harness_PI_get_parameter_value(&precompiled_param_id, &int_type, &value);

            const bool precompiled_ok =
               value.kind == OBCP_Parameter_Value_int_value_PRESENT &&
               value.u.int_value == 1234;

            test_record(T_PRECOMPILED, precompiled_ok);
            if (precompiled_ok) {
               printf("Precompiled OBCP test PASSED: parameter %u updated to %d\n",
                      (unsigned)precompiled_param_id,
                      (int)value.u.int_value);
            } else {
               harness_error_printf("Precompiled OBCP test FAILED: parameter %u expected 1234, got %d\n",
                                    (unsigned)precompiled_param_id,
                                    value.kind == OBCP_Parameter_Value_int_value_PRESENT ?
                                       (int)value.u.int_value : -1);
            }

            unload_precompiled_obcp(&OBCP_PRECOMPILED_TEST);
            test_record(T_LOAD_LIMIT, run_load_limit_test());
            report_final_results();
            printf("All tests finished — exiting\n");
            kill(getpid(), SIGTERM);
         }
         break;
      }

      default:
         harness_report_failure_and_exit("Harness ERROR: unexpected phase %d\n", (int)phase);
         return;
   }
}


